import type { HelpCatalog, HelpCategory, HelpUiCopy } from "../types";
import { buildArticles, categories, type LocalizedArticle } from "./shared";

type Language = "en" | "th" | "ja" | "zh-CN";

type Topic = {
  id: string;
  category: HelpCategory;
  route: string;
  href: string;
  title: string;
  summary: string;
  steps: string[];
  action: string;
};

function article(topic: Topic): LocalizedArticle {
  return {
    id: topic.id,
    category: topic.category,
    routes: [topic.route],
    title: topic.title,
    summary: topic.summary,
    steps: topic.steps.map((instruction) => ({
      title: "",
      instruction,
      result: "",
    })),
    troubleshooting: [],
    related: [],
    keywords: `${topic.title} ${topic.summary}`
      .toLocaleLowerCase()
      .replace(/\*\*/g, "")
      .split(/\s+/),
    action: { label: topic.action, href: topic.href },
  };
}

const sharedUi = {
  searchStatus: (count: number) =>
    `${count} ${count === 1 ? "topic" : "topics"}`,
  categories: categories.en,
  expectedResult: "Result",
  troubleshooting: "Help",
  related: "Related",
  imageUnavailable: "Image unavailable",
  copied: "Link copied",
  copyLink: "Copy direct link",
  smallerText: "Use smaller help text",
  largerText: "Use larger help text",
  loading: "Loading help",
  contentUnavailable: "Help could not be loaded.",
  retry: "Try again",
};

function helpUi(locale: Language): HelpUiCopy {
  if (locale === "th")
    return {
      ...sharedUi,
      trigger: "ช่วยเหลือ",
      triggerAriaLabel: "เปิดคู่มือเว็บไซต์",
      heading: "วิธีใช้เว็บไซต์",
      guideDescription: "เลือกหัวข้อแล้วทำตามขั้นตอนสั้น ๆ",
      close: "ปิดคู่มือ",
      searchLabel: "ค้นหาคู่มือ",
      searchPlaceholder: "ค้นหาหัวข้อ",
      searchStatus: (count) => `พบ ${count} หัวข้อ`,
      suggested: "แนะนำสำหรับหน้านี้",
      allTopics: "หัวข้อทั้งหมด",
      categories: categories.th,
      back: "กลับไปหัวข้อทั้งหมด",
      breadcrumb: "หัวข้อช่วยเหลือ",
      steps: "ขั้นตอน",
      noResults: "ไม่พบหัวข้อที่ตรงกับคำค้น",
      resetSearch: "ล้างคำค้น",
    };
  if (locale === "ja")
    return {
      ...sharedUi,
      trigger: "ヘルプ",
      triggerAriaLabel: "ウェブサイトのヘルプを開く",
      heading: "ウェブサイトの使い方",
      guideDescription: "項目を選び、短い手順に従ってください。",
      close: "ヘルプを閉じる",
      searchLabel: "ヘルプを検索",
      searchPlaceholder: "項目を検索",
      searchStatus: (count) => `${count}件`,
      suggested: "このページのおすすめ",
      allTopics: "すべての項目",
      categories: categories.ja,
      back: "すべての項目に戻る",
      breadcrumb: "ヘルプ項目",
      steps: "手順",
      noResults: "一致する項目がありません。",
      resetSearch: "検索を消去",
    };
  if (locale === "zh-CN")
    return {
      ...sharedUi,
      trigger: "帮助",
      triggerAriaLabel: "打开网站帮助",
      heading: "网站使用方法",
      guideDescription: "选择一个主题并按简短步骤操作。",
      close: "关闭帮助",
      searchLabel: "搜索帮助",
      searchPlaceholder: "搜索主题",
      searchStatus: (count) => `${count} 个主题`,
      suggested: "此页面的建议",
      allTopics: "全部主题",
      categories: categories["zh-CN"],
      back: "返回全部主题",
      breadcrumb: "帮助主题",
      steps: "步骤",
      noResults: "没有匹配的主题。",
      resetSearch: "清除搜索",
    };
  return {
    ...sharedUi,
    trigger: "Help",
    triggerAriaLabel: "Open website help",
    heading: "How to use this website",
    guideDescription: "Choose a topic and follow the short steps.",
    close: "Close help",
    searchLabel: "Search help",
    searchPlaceholder: "Search topics",
    suggested: "Suggested for this page",
    allTopics: "All topics",
    back: "Back to all topics",
    breadcrumb: "Help topics",
    steps: "Steps",
    noResults: "No topics match your search.",
    resetSearch: "Clear search",
  };
}

/**
 * Steps name the exact place or control to select and wrap it in `**…**`, so
 * the help panel prints it in bold. Every name must match the website word for
 * word.
 */
const en: Topic[] = [
  {
    id: "public-new-profile",
    category: "student-records",
    route: "/student-records",
    href: "/student-records?task=profile",
    title: "How do I make a new student profile?",
    summary: "Request a student profile for RenShinKan review.",
    steps: [
      "Open **New profile** in the student workspace.",
      "Enter the student details and choose the correct dojo.",
      "Check the **Review and create** summary, then choose **Create student profile**.",
    ],
    action: "Create a student profile",
  },
  {
    id: "public-exam-application",
    category: "examinations",
    route: "/student-records",
    href: "/student-records?task=exam",
    title: "How do I fill out an exam application?",
    summary: "Submit an application for an available examination.",
    steps: [
      "Open **Exam application** in the student workspace.",
      "Enter your **Student ID** and complete every required question.",
      "Choose **Review every answer**, check the summary, then choose **Submit application** and pay the fee shown.",
    ],
    action: "Open exam application",
  },
  {
    id: "public-passport",
    category: "student-records",
    route: "/student-records",
    href: "/student-records",
    title: "How do I see my student passport?",
    summary: "Open the private student passport.",
    steps: [
      "Open **My passport** in the student workspace.",
      "Enter your **Student name** and **Student ID**.",
      "Choose **Find my record**, then use the passport tabs.",
    ],
    action: "Find my passport",
  },
  {
    id: "public-monthly",
    category: "payments",
    route: "/support",
    href: "/support#monthly-contribution",
    title: "How do I pay monthly dojo contributions?",
    summary: "Pay and submit proof for a monthly RenShinKan contribution.",
    steps: [
      "Open **Support** from the menu and go to the contribution form.",
      "Choose **Monthly dojo contribution**, then add every student covered by the payment.",
      "Continue to the PromptPay QR, pay the amount shown, then upload your payment proof.",
    ],
    action: "Pay a monthly contribution",
  },
  {
    id: "public-aat",
    category: "payments",
    route: "/student-records",
    href: "/student-records",
    title: "How do I pay an AAT annual contribution?",
    summary:
      "Register for AAT when needed, then submit the annual contribution.",
    steps: [
      "Open **My passport** and check the **Contributions** tab.",
      "If you have no AAT number yet, use the AAT registration link shown there first.",
      "On the contribution form choose **AAT annual contribution**, pay the amount shown, then upload a clear payment proof.",
    ],
    action: "Open student records",
  },
  {
    id: "public-contact",
    category: "support",
    route: "/contact",
    href: "/contact",
    title: "How do I contact the dojo?",
    summary: "Send RenShinKan a question or visit enquiry.",
    steps: [
      "Open **Contact Us** from the menu.",
      "Choose the contact method that suits you.",
      "Include your name and a short, clear message.",
    ],
    action: "Contact the dojo",
  },
  {
    id: "public-donation",
    category: "support",
    route: "/support",
    href: "/support#donations",
    title: "How do I make a donation?",
    summary: "Support the community dojo with a one-time donation.",
    steps: [
      "Open **Support** from the menu and go to the **Donations** section.",
      "Read the payment details, or contact the dojo for PromptPay.",
      "Send the donation and keep your payment confirmation.",
    ],
    action: "View donation details",
  },
  {
    id: "public-newsletter",
    category: "news-resources",
    route: "/newsletter",
    href: "/newsletter",
    title: "How do I read dojo newsletters?",
    summary: "Read the latest update and browse the archive.",
    steps: [
      "Open **Newsletter** from the menu or homepage.",
      "Choose **Read newsletter** on the update you want.",
      "Use the archive filters to find older updates.",
    ],
    action: "Read newsletters",
  },
  {
    id: "public-newsletter-email",
    category: "news-resources",
    route: "/newsletter",
    href: "/newsletter#newsletter-signup",
    title: "How do I receive newsletters by email?",
    summary: "Subscribe to published dojo updates.",
    steps: [
      "Open **Newsletter** from the menu and scroll to the signup section.",
      "Choose **Open signup form**, then enter your email address.",
      "Submit the form and follow any confirmation message.",
    ],
    action: "Receive updates by email",
  },
  {
    id: "public-training-hours",
    category: "student-records",
    route: "/student-records",
    href: "/student-records",
    title: "How to request training hours",
    summary:
      "Ask a sensei to verify training completed outside your current total.",
    steps: [
      "Open **My passport** in the student workspace and find your record.",
      "Go to **Submit additional training hours** below your passport.",
      "Enter the training date, hours, and details, then choose **Submit for review**. Approved hours appear in your passport.",
    ],
    action: "Request training hours",
  },
  {
    id: "public-join",
    category: "getting-started",
    route: "/classes",
    href: "/classes#first-visit",
    title: "How do I join the dojo and start training?",
    summary: "Visit a class first, then begin training with RenShinKan.",
    steps: [
      "Open **Classes** from the menu, then **First Visit Guide**.",
      "Read the short first-day steps and what to bring.",
      "Choose **Ask About Visiting** to tell the dojo when you would like to come.",
    ],
    action: "See the first visit guide",
  },
  {
    id: "public-class-times",
    category: "training",
    route: "/classes",
    href: "/classes#schedule",
    title: "When are the classes?",
    summary: "See the weekly class times and when to arrive.",
    steps: [
      "Open **Classes** from the menu, then **Class Schedule**.",
      "Check the day and time of each session.",
      "Read the note under the times and arrive early to help prepare the dojo.",
    ],
    action: "See class times",
  },
  {
    id: "public-belt-exams",
    category: "examinations",
    route: "/classes",
    href: "/classes#belt-exams",
    title: "How do belt exams and ranks work?",
    summary: "See the belt levels and the next examination announcement.",
    steps: [
      "Open **Classes** from the menu, then **Belt Exams**.",
      "Read the announcement and the belt chart.",
      "Choose **Download PDF form** if you need the paper application.",
    ],
    action: "See belt levels",
  },
  {
    id: "public-faq",
    category: "support",
    route: "/classes",
    href: "/classes#faq",
    title: "Where do I find answers to common questions?",
    summary: "Read the questions people ask before a first class.",
    steps: [
      "Open **Classes** from the menu, then **FAQ**.",
      "Choose a question to open its answer.",
      "If your question is not answered, open **Contact Us**.",
    ],
    action: "Read common questions",
  },
  {
    id: "public-photos",
    category: "news-resources",
    route: "/",
    href: "/#dojo-photos",
    title: "Where can I see photos of the dojo?",
    summary: "Look through dojo, class, and event photographs.",
    steps: [
      "Open **Our Dojo** from the menu, then **Dojo Photos**.",
      "Scroll through the mat, grounds, and group photographs.",
      "For event photographs open **Community**, then **Past Events**.",
    ],
    action: "See dojo photos",
  },
  {
    id: "public-community",
    category: "news-resources",
    route: "/community",
    href: "/community#past-events",
    title: "Where can I read about dojo events and partners?",
    summary: "See past events, the foundation, and the university club.",
    steps: [
      "Open **Community** from the menu, then **Past Events**.",
      "Look through the event albums and dates.",
      "Continue to **Peace Culture Foundation** and **Chiang Mai CMU**.",
    ],
    action: "See community events",
  },
  {
    id: "public-workshops",
    category: "news-resources",
    route: "/workshops",
    href: "/workshops",
    title: "How do I find workshops and seminars?",
    summary: "See the dojo workshops and where new dates appear.",
    steps: [
      "Choose **View workshops** below to open the workshop page.",
      "Read each workshop card to see what it covers.",
      "Choose **View Dojo Updates** for new dates.",
    ],
    action: "View workshops",
  },
  {
    id: "public-downloads",
    category: "news-resources",
    route: "/downloads",
    href: "/downloads",
    title: "How do I get dojo forms and PDF files?",
    summary: "Open the official forms and grading references.",
    steps: [
      "Open **Support** from the menu, then **Downloads**.",
      "Find the form or reference you need in the list.",
      "Choose **Open or download PDF**.",
    ],
    action: "Open downloads",
  },
  {
    id: "public-location",
    category: "getting-started",
    route: "/",
    href: "/#location",
    title: "Where is the dojo and how do I get there?",
    summary: "Find the dojo address and open the map.",
    steps: [
      "Open **Our Dojo** from the menu, then **Location**.",
      "Read the dojo address.",
      "Choose **Open Map** for directions.",
    ],
    action: "Find the dojo",
  },
  {
    id: "public-instructors",
    category: "getting-started",
    route: "/",
    href: "/#instructors",
    title: "Who teaches the classes?",
    summary: "Read about the RenShinKan instructors.",
    steps: [
      "Open **Our Dojo** from the menu, then **Instructors**.",
      "Read the short introduction for each instructor.",
      "For more questions open **Contact Us**.",
    ],
    action: "Meet the instructors",
  },
  {
    id: "public-aikido",
    category: "getting-started",
    route: "/aikido",
    href: "/aikido#what-is-aikido",
    title: "What is aikido?",
    summary: "Read a short introduction to aikido and its history.",
    steps: [
      "Open **Aikido** from the menu, then **What Is Aikido**.",
      "Read the introduction, then the history section.",
      "For beginner questions open **Classes**, then **FAQ**.",
    ],
    action: "Read about aikido",
  },
  {
    id: "public-language",
    category: "getting-started",
    route: "/",
    href: "/",
    title: "How do I read this website in another language?",
    summary: "Change the website language at any time.",
    steps: [
      "Find the language button at the top of every page.",
      "Choose **English**, **ไทย**, **日本語**, or **中文**.",
      "The page you are reading stays open in the new language.",
    ],
    action: "Open the home page",
  },
  {
    id: "public-payment-proof",
    category: "payments",
    route: "/support",
    href: "/support#monthly-contribution",
    title: "How do I send proof that I paid?",
    summary: "Upload your payment slip so the dojo can confirm the payment.",
    steps: [
      "After you pay, stay on the same page and find **Upload payment proof**.",
      "Choose **Choose payment proof file**, then pick the photo or PDF of your slip.",
      "Choose **Upload selected file**. A sensei checks it and updates your payment.",
    ],
    action: "Upload payment proof",
  },
  {
    id: "public-pay-many-students",
    category: "payments",
    route: "/support",
    href: "/support#monthly-contribution",
    title: "How do I pay for more than one student?",
    summary:
      "Cover several students, such as brothers and sisters, in one payment.",
    steps: [
      "Open **Support** from the menu and find **Who is this payment for?**",
      "Choose **Add another student**, then enter each **Student ID** and name.",
      "Check **Total to pay**, continue to the PromptPay QR, and pay that amount.",
    ],
    action: "Pay for several students",
  },
  {
    id: "public-contribution-amount",
    category: "payments",
    route: "/support",
    href: "/support#monthly-contribution",
    title: "How much is the monthly contribution?",
    summary: "See the amount before you pay anything.",
    steps: [
      "Open **Support** from the menu and read **What would you like to pay?**",
      "Choose **Monthly dojo contribution** or **AAT annual contribution** to see each amount.",
      "**Total to pay** shows the full amount for every student you added.",
    ],
    action: "See the amount",
  },
  {
    id: "public-payment-status",
    category: "payments",
    route: "/student-records",
    href: "/student-records",
    title: "How do I check if my payment was accepted?",
    summary: "See whether the dojo has confirmed a payment yet.",
    steps: [
      "Open **My passport** in the student workspace and find your record.",
      "Open the **Contributions** tab.",
      "Each payment shows **Under review**, **Verified**, or **Action needed**.",
    ],
    action: "Check my payments",
  },
  {
    id: "public-student-id",
    category: "student-records",
    route: "/student-records",
    href: "/student-records?task=profile",
    title: "Where do I find my Student ID?",
    summary: "Your Student ID is given when your profile is created.",
    steps: [
      "The Student ID appears as soon as you choose **Create student profile**.",
      "Choose **Copy ID** and keep it somewhere safe. It looks like RSK-6901.",
      "If you lose it, open **Contact Us** and ask the dojo.",
    ],
    action: "Create a student profile",
  },
  {
    id: "public-profile-review",
    category: "student-records",
    route: "/student-records",
    href: "/student-records?task=profile",
    title: "What happens after I create my profile?",
    summary: "Your profile works straight away while a sensei checks it.",
    steps: [
      "After you choose **Create student profile**, you can use the profile at once.",
      "The status stays **Pending administrator review** until a sensei checks it.",
      "If the Student ID is corrected, your first ID still opens the same profile.",
    ],
    action: "Create a student profile",
  },
  {
    id: "public-profile-photo",
    category: "student-records",
    route: "/student-records",
    href: "/student-records",
    title: "How do I add a photo to my profile?",
    summary: "Put a portrait on your student passport.",
    steps: [
      "On the new profile form, choose **Choose profile photo**.",
      "To change it later, open **My passport**, find your record, then choose **Change profile photo**.",
      "Use a clear portrait. JPEG, PNG, or WebP, up to 8 MB.",
    ],
    action: "Open my passport",
  },
  {
    id: "public-share-record",
    category: "student-records",
    route: "/student-records",
    href: "/student-records",
    title: "How do I share or print my training record?",
    summary: "Send your record to another dojo, or print it on paper.",
    steps: [
      "Open **My passport** in the student workspace and find your record.",
      "Go to **Student record QR** below your passport.",
      "Choose **Copy link**, **Share**, **Download QR**, or **Print**.",
    ],
    action: "Open my passport",
  },
  {
    id: "public-exam-status",
    category: "examinations",
    route: "/student-records",
    href: "/student-records",
    title: "How do I check my exam application?",
    summary: "See the exams and results already on your record.",
    steps: [
      "Open **My passport** in the student workspace and find your record.",
      "Open the **Examination History** tab.",
      "Recorded exams and results appear here after a sensei enters them.",
    ],
    action: "Check my exams",
  },
  {
    id: "public-exam-fee",
    category: "examinations",
    route: "/student-records",
    href: "/student-records?task=exam",
    title: "How much does a belt exam cost?",
    summary: "The fee depends on the rank you apply for.",
    steps: [
      "Open **Exam application** in the student workspace.",
      "Choose **Rank you are applying to test for**. The fee is shown under it.",
      "The same fee appears again on **Review your application** before you submit.",
    ],
    action: "Open exam application",
  },
  {
    id: "public-what-to-bring",
    category: "getting-started",
    route: "/classes",
    href: "/classes#first-visit",
    title: "What should I wear and bring to my first class?",
    summary: "What to wear, when to arrive, and what to do on the mat.",
    steps: [
      "Open **Classes** from the menu, then **First Visit Guide**.",
      "Wear loose trousers and a comfortable shirt. A keikogi is only needed once you feel ready.",
      "Arrive early, take your shoes off before the mat, and wash your feet.",
    ],
    action: "Read the first visit guide",
  },
  {
    id: "public-children",
    category: "getting-started",
    route: "/classes",
    href: "/classes#faq",
    title: "Can my child train, and can I watch?",
    summary: "Children are welcome, and parents can watch from the deck.",
    steps: [
      "Open **Classes** from the menu, then **FAQ**.",
      "Open **What age is welcome?** and **Is aikido safe for children?**",
      "Open **Can parents watch?** The dojo has a viewing deck with seating.",
    ],
    action: "Read about children's classes",
  },
  {
    id: "public-who-can-practice",
    category: "getting-started",
    route: "/aikido",
    href: "/aikido#who-can-practice",
    title: "Can I start if I have never trained before?",
    summary: "Aikido has no competition and welcomes new students of any age.",
    steps: [
      "Choose **Who Can Practice?** below to open that part of the aikido page.",
      "Read the part about children, then the part about adults.",
      "Then open **Classes**, then **First Visit Guide**, to plan your first day.",
    ],
    action: "Who Can Practice?",
  },
  {
    id: "public-dojo-history",
    category: "news-resources",
    route: "/",
    href: "/#dojo-history",
    title: "How was the dojo built?",
    summary: "See how RenShinKan grew from an empty plot of land.",
    steps: [
      "Open **Our Dojo** from the menu, then **Dojo History**.",
      "Look through the building photographs in order.",
      "Choose **Source Gallery** at the end for more pictures.",
    ],
    action: "See the dojo history",
  },
  {
    id: "public-o-sensei",
    category: "getting-started",
    route: "/aikido",
    href: "/aikido#o-sensei",
    title: "Who started aikido?",
    summary: "Read about O Sensei, the founder of aikido.",
    steps: [
      "Open **Aikido** from the menu, then **O Sensei**.",
      "Read the short story of the founder.",
      "For the wider story choose **History of Aikido**.",
    ],
    action: "Read about O Sensei",
  },
  {
    id: "public-exam-photos",
    category: "news-resources",
    route: "/classes",
    href: "/classes#gallery",
    title: "Where can I see belt exam photos?",
    summary: "Look at photographs from past gradings.",
    steps: [
      "Open **Classes** from the menu, then **Gallery**.",
      "Choose an album to open the photographs.",
      "For dojo and event photographs open **Our Dojo**, then **Dojo Photos**.",
    ],
    action: "See belt exam photos",
  },
  {
    id: "public-newsletter-find",
    category: "news-resources",
    route: "/newsletter",
    href: "/newsletter",
    title: "How do I find an older newsletter?",
    summary: "Search the newsletter archive by word, subject, or year.",
    steps: [
      "Open **Newsletter** from the menu and scroll to **All newsletters**.",
      "Type a word in **Search newsletters**, or pick a **Category** or **Year**.",
      "Choose **Clear filters** to start again.",
    ],
    action: "Search the archive",
  },
  {
    id: "public-privacy",
    category: "support",
    route: "/student-records",
    href: "/contact",
    title: "Is my personal information kept private?",
    summary: "How the website handles your name, ID, and payment proof.",
    steps: [
      "Your **Student name** and **Student ID** are sent securely and never placed in the page address.",
      "A shared profile link never allows editing, and never shows application answers or payment details.",
      "Payment proof is kept as a private record. To ask anything else, open **Contact Us**.",
    ],
    action: "Contact the dojo",
  },
];

const th: Topic[] = [
  {
    ...en[0],
    title: "สร้างโปรไฟล์นักเรียนใหม่อย่างไร?",
    summary: "ส่งคำขอโปรไฟล์ให้อาจารย์ RenShinKan ตรวจสอบ",
    steps: [
      "เปิด **โปรไฟล์ใหม่** ในพื้นที่นักเรียน",
      "กรอกข้อมูลนักเรียนและเลือกโดโจให้ถูกต้อง",
      "ตรวจสอบสรุปใน **ตรวจสอบและสร้าง** แล้วเลือก **สร้างโปรไฟล์นักเรียน**",
    ],
    action: "สร้างโปรไฟล์นักเรียน",
  },
  {
    ...en[1],
    title: "กรอกใบสมัครสอบอย่างไร?",
    summary: "ส่งใบสมัครสำหรับการสอบที่เปิดรับ",
    steps: [
      "เปิด **ใบสมัครสอบ** ในพื้นที่นักเรียน",
      "กรอก **รหัสนักเรียน** และข้อมูลที่จำเป็นทุกข้อ",
      "เลือก **ตรวจสอบทุกคำตอบ** ดูสรุป แล้วส่งใบสมัครและชำระค่าธรรมเนียม",
    ],
    action: "เปิดใบสมัครสอบ",
  },
  {
    ...en[2],
    title: "ดูพาสปอร์ตนักเรียนอย่างไร?",
    summary: "เปิดพาสปอร์ตนักเรียนแบบส่วนตัว",
    steps: [
      "เปิด **พาสปอร์ตของฉัน** ในพื้นที่นักเรียน",
      "กรอก **ชื่อนักเรียน** และ **รหัสนักเรียน**",
      "เลือก **ค้นหาประวัติของฉัน** แล้วใช้แท็บในพาสปอร์ต",
    ],
    action: "ค้นหาพาสปอร์ต",
  },
  {
    ...en[3],
    title: "ชำระเงินสมทบรายเดือนอย่างไร?",
    summary: "ชำระและส่งหลักฐานเงินสมทบรายเดือน",
    steps: [
      "เปิด **สนับสนุน** จากเมนู แล้วไปที่แบบฟอร์มเงินสมทบ",
      "เลือก **เงินสมทบโดโจรายเดือน** แล้วกรอกนักเรียนทุกคนที่รวมอยู่ในการชำระเงิน",
      "ไปต่อที่คิวอาร์ PromptPay ชำระตามยอดที่แสดง แล้วอัปโหลดหลักฐาน",
    ],
    action: "ชำระเงินสมทบรายเดือน",
  },
  {
    ...en[4],
    title: "ชำระเงินสมทบ AAT รายปีอย่างไร?",
    summary: "ลงทะเบียน AAT ก่อนหากยังไม่มีเลขสมาชิก แล้วส่งเงินสมทบ",
    steps: [
      "เปิด **พาสปอร์ตของฉัน** แล้วดูแท็บ **เงินสมทบ**",
      "หากยังไม่มีเลข AAT ให้ใช้ลิงก์ลงทะเบียน AAT ที่แสดงไว้ก่อน",
      "ในแบบฟอร์มเงินสมทบเลือก **เงินสมทบรายปี AAT** ชำระตามยอดที่แสดง แล้วอัปโหลดหลักฐานที่ชัดเจน",
    ],
    action: "เปิดข้อมูลนักเรียน",
  },
  {
    ...en[5],
    title: "ติดต่อโดโจอย่างไร?",
    summary: "ส่งคำถามหรือนัดหมายเยี่ยมชม RenShinKan",
    steps: [
      "เปิด **ติดต่อเรา** จากเมนู",
      "เลือกช่องทางติดต่อที่สะดวก",
      "แจ้งชื่อและข้อความสั้น ๆ ที่ชัดเจน",
    ],
    action: "ติดต่อโดโจ",
  },
  {
    ...en[6],
    title: "บริจาคให้โดโจอย่างไร?",
    summary: "สนับสนุนโดโจชุมชนด้วยการบริจาคครั้งเดียว",
    steps: [
      "เปิด **สนับสนุน** จากเมนู แล้วไปที่ส่วน **การบริจาค**",
      "อ่านข้อมูลการชำระหรือติดต่อโดโจเพื่อขอ PromptPay",
      "ส่งเงินบริจาคและเก็บหลักฐานไว้",
    ],
    action: "ดูข้อมูลการบริจาค",
  },
  {
    ...en[7],
    title: "อ่านจดหมายข่าวโดโจอย่างไร?",
    summary: "อ่านข่าวล่าสุดและดูคลังข่าว",
    steps: [
      "เปิด **จดหมายข่าว** จากเมนูหรือหน้าแรก",
      "เลือก **อ่านจดหมายข่าว** ในฉบับที่ต้องการ",
      "ใช้ตัวกรองคลังข่าวเพื่อดูข่าวเก่า",
    ],
    action: "อ่านจดหมายข่าว",
  },
  {
    ...en[8],
    title: "รับจดหมายข่าวทางอีเมลอย่างไร?",
    summary: "สมัครรับข่าวที่เผยแพร่จากโดโจ",
    steps: [
      "เปิด **จดหมายข่าว** จากเมนู แล้วเลื่อนไปที่ส่วนสมัครรับข่าว",
      "เลือก **เปิดแบบฟอร์มสมัคร** แล้วกรอกอีเมลของคุณ",
      "ส่งแบบฟอร์มและทำตามข้อความยืนยัน",
    ],
    action: "รับข่าวทางอีเมล",
  },
  {
    ...en[9],
    title: "วิธีขอเพิ่มชั่วโมงฝึก",
    summary: "ขอให้อาจารย์ตรวจสอบชั่วโมงการฝึกที่ยังไม่รวมอยู่ในยอดปัจจุบัน",
    steps: [
      "เปิด **พาสปอร์ตของฉัน** ในพื้นที่นักเรียน แล้วค้นหาประวัติของคุณ",
      "ไปที่ **ส่งชั่วโมงฝึกเพิ่มเติม** ใต้พาสปอร์ต",
      "กรอกวันที่ฝึก จำนวนชั่วโมง และรายละเอียด แล้วเลือก **ส่งเพื่อตรวจสอบ** ชั่วโมงที่อนุมัติจะแสดงในพาสปอร์ต",
    ],
    action: "ขอตรวจสอบชั่วโมงฝึก",
  },
  {
    ...en[10],
    title: "สมัครเข้าฝึกกับโดโจอย่างไร?",
    summary: "มาดูชั้นเรียนก่อน แล้วจึงเริ่มฝึกกับ RenShinKan",
    steps: [
      "เปิด **ชั้นเรียน** จากเมนู แล้วเลือก **คู่มือการเยี่ยมชมครั้งแรก**",
      "อ่านขั้นตอนของวันแรกและสิ่งที่ต้องเตรียม",
      "เลือก **ถามเกี่ยวกับการเยี่ยมชม** เพื่อแจ้งวันที่คุณสะดวกมา",
    ],
    action: "ดูคู่มือการเยี่ยมชมครั้งแรก",
  },
  {
    ...en[11],
    title: "ชั้นเรียนมีวันและเวลาใดบ้าง?",
    summary: "ดูตารางเรียนรายสัปดาห์และเวลาที่ควรมาถึง",
    steps: [
      "เปิด **ชั้นเรียน** จากเมนู แล้วเลือก **ตารางเรียน**",
      "ดูวันและเวลาของแต่ละคาบ",
      "อ่านหมายเหตุใต้ตาราง และมาถึงก่อนเวลาเพื่อช่วยเตรียมโดโจ",
    ],
    action: "ดูตารางเรียน",
  },
  {
    ...en[12],
    title: "การสอบเข็มขัดและระดับขั้นเป็นอย่างไร?",
    summary: "ดูระดับเข็มขัดและประกาศการสอบครั้งถัดไป",
    steps: [
      "เปิด **ชั้นเรียน** จากเมนู แล้วเลือก **การสอบเข็มขัด**",
      "อ่านประกาศและตารางระดับเข็มขัด",
      "เลือก **ดาวน์โหลดแบบฟอร์ม PDF** หากต้องการใบสมัครแบบกระดาษ",
    ],
    action: "ดูระดับเข็มขัด",
  },
  {
    ...en[13],
    title: "หาคำตอบของคำถามที่พบบ่อยได้ที่ไหน?",
    summary: "อ่านคำถามที่คนมักถามก่อนเรียนครั้งแรก",
    steps: [
      "เปิด **ชั้นเรียน** จากเมนู แล้วเลือก **คำถามที่พบบ่อย**",
      "เลือกคำถามเพื่อเปิดคำตอบ",
      "หากไม่มีคำตอบที่ต้องการ ให้เปิด **ติดต่อเรา**",
    ],
    action: "อ่านคำถามที่พบบ่อย",
  },
  {
    ...en[14],
    title: "ดูภาพถ่ายของโดโจได้ที่ไหน?",
    summary: "ชมภาพโดโจ ภาพชั้นเรียน และภาพกิจกรรม",
    steps: [
      "เปิด **โดโจของเรา** จากเมนู แล้วเลือก **ภาพถ่ายโดโจ**",
      "เลื่อนดูภาพบนเบาะ ภาพบริเวณโดโจ และภาพหมู่",
      "สำหรับภาพกิจกรรม ให้เปิด **ชุมชน** แล้วเลือก **เหตุการณ์ที่ผ่านมา**",
    ],
    action: "ดูภาพถ่ายโดโจ",
  },
  {
    ...en[15],
    title: "อ่านเรื่องกิจกรรมและเครือข่ายของโดโจได้ที่ไหน?",
    summary: "ดูกิจกรรมที่ผ่านมา มูลนิธิ และชมรมของมหาวิทยาลัย",
    steps: [
      "เปิด **ชุมชน** จากเมนู แล้วเลือก **เหตุการณ์ที่ผ่านมา**",
      "ชมอัลบั้มภาพและวันที่ของแต่ละกิจกรรม",
      "เลื่อนต่อไปที่ **มูลนิธิวัฒนธรรมสันติ** และ **มช.เชียงใหม่**",
    ],
    action: "ดูกิจกรรมของชุมชน",
  },
  {
    ...en[16],
    title: "หาเวิร์กช็อปและการอบรมพิเศษได้อย่างไร?",
    summary: "ดูเวิร์กช็อปของโดโจและที่ประกาศวันใหม่",
    steps: [
      "เลือก **ดูเวิร์กช็อป** ด้านล่างเพื่อเปิดหน้าเวิร์กช็อป",
      "อ่านรายละเอียดในการ์ดของแต่ละเวิร์กช็อป",
      "เลือก **ดูอัปเดตของโดโจ** เพื่อดูวันใหม่",
    ],
    action: "ดูเวิร์กช็อป",
  },
  {
    ...en[17],
    title: "ดาวน์โหลดแบบฟอร์มและไฟล์ PDF ของโดโจอย่างไร?",
    summary: "เปิดแบบฟอร์มทางการและเอกสารอ้างอิงการสอบ",
    steps: [
      "เปิด **สนับสนุน** จากเมนู แล้วเลือก **ดาวน์โหลด**",
      "ค้นหาแบบฟอร์มหรือเอกสารที่ต้องการในรายการ",
      "เลือก **Open or download PDF**",
    ],
    action: "เปิดหน้าดาวน์โหลด",
  },
  {
    ...en[18],
    title: "โดโจอยู่ที่ไหน และเดินทางอย่างไร?",
    summary: "ดูที่อยู่ของโดโจและเปิดแผนที่",
    steps: [
      "เปิด **โดโจของเรา** จากเมนู แล้วเลือก **ที่ตั้ง**",
      "อ่านที่อยู่ของโดโจ",
      "เลือก **เปิดแผนที่** เพื่อดูเส้นทาง",
    ],
    action: "ค้นหาโดโจ",
  },
  {
    ...en[19],
    title: "ใครเป็นผู้สอนในชั้นเรียน?",
    summary: "อ่านประวัติสั้น ๆ ของอาจารย์ RenShinKan",
    steps: [
      "เปิด **โดโจของเรา** จากเมนู แล้วเลือก **อาจารย์ผู้สอน**",
      "อ่านคำแนะนำสั้น ๆ ของอาจารย์แต่ละท่าน",
      "หากมีคำถามเพิ่มเติม ให้เปิด **ติดต่อเรา**",
    ],
    action: "รู้จักอาจารย์ผู้สอน",
  },
  {
    ...en[20],
    title: "ไอคิโดคืออะไร?",
    summary: "อ่านคำอธิบายสั้น ๆ เรื่องไอคิโดและความเป็นมา",
    steps: [
      "เปิด **ไอคิโด** จากเมนู แล้วเลือก **ไอคิโดคืออะไร**",
      "อ่านบทนำ แล้วอ่านส่วนประวัติความเป็นมา",
      "หากเป็นคำถามสำหรับผู้เริ่มต้น ให้เปิด **ชั้นเรียน** แล้วเลือก **คำถามที่พบบ่อย**",
    ],
    action: "อ่านเรื่องไอคิโด",
  },
  {
    ...en[21],
    title: "อ่านเว็บไซต์นี้เป็นภาษาอื่นอย่างไร?",
    summary: "เปลี่ยนภาษาของเว็บไซต์ได้ทุกเมื่อ",
    steps: [
      "มองหาปุ่มภาษาที่ด้านบนของทุกหน้า",
      "เลือก **English**, **ไทย**, **日本語** หรือ **中文**",
      "หน้าที่คุณอ่านอยู่จะแสดงเป็นภาษาใหม่ทันที",
    ],
    action: "เปิดหน้าแรก",
  },
  {
    ...en[22],
    title: "ส่งหลักฐานการชำระเงินอย่างไร?",
    summary: "อัปโหลดสลิปเพื่อให้โดโจยืนยันการชำระเงินของคุณได้",
    steps: [
      "หลังชำระเงินแล้ว ให้อยู่ที่หน้าเดิม แล้วมองหา **อัปโหลดหลักฐานการชำระเงิน**",
      "เลือก **เลือกไฟล์หลักฐานการชำระเงิน** แล้วเลือกรูปภาพหรือไฟล์ PDF ของสลิป",
      "เลือก **อัปโหลดไฟล์ที่เลือก** อาจารย์จะตรวจสอบและอัปเดตสถานะการชำระเงินให้",
    ],
    action: "อัปโหลดหลักฐานการชำระเงิน",
  },
  {
    ...en[23],
    title: "ชำระเงินให้นักเรียนหลายคนพร้อมกันอย่างไร?",
    summary: "รวมนักเรียนหลายคน เช่น พี่น้อง ไว้ในการชำระเงินครั้งเดียว",
    steps: [
      "เปิด **สนับสนุน** จากเมนู แล้วไปที่ **การชำระเงินนี้สำหรับใคร**",
      "เลือก **เพิ่มนักเรียนอีกคน** แล้วกรอก **รหัสนักเรียน** และชื่อของแต่ละคน",
      "ตรวจสอบ **ยอดรวมที่ต้องชำระ** ไปต่อที่คิวอาร์ PromptPay แล้วชำระตามยอดนั้น",
    ],
    action: "ชำระให้นักเรียนหลายคน",
  },
  {
    ...en[24],
    title: "เงินสมทบรายเดือนเท่าไหร่?",
    summary: "ดูจำนวนเงินก่อนชำระจริง",
    steps: [
      "เปิด **สนับสนุน** จากเมนู แล้วดูหัวข้อ **คุณต้องการชำระรายการใด**",
      "เลือก **เงินสมทบโดโจรายเดือน** หรือ **เงินสมทบรายปี AAT** เพื่อดูจำนวนเงินของแต่ละแบบ",
      "**ยอดรวมที่ต้องชำระ** จะแสดงจำนวนเงินทั้งหมดของนักเรียนที่คุณเพิ่มไว้",
    ],
    action: "ดูจำนวนเงิน",
  },
  {
    ...en[25],
    title: "ตรวจสอบว่าการชำระเงินได้รับการยืนยันแล้วหรือยัง?",
    summary: "ดูว่าโดโจยืนยันการชำระเงินของคุณแล้วหรือไม่",
    steps: [
      "เปิด **พาสปอร์ตของฉัน** ในพื้นที่นักเรียน แล้วค้นหาประวัติของคุณ",
      "เปิดแท็บ **เงินสมทบ**",
      "แต่ละรายการจะแสดง **กำลังตรวจสอบ**, **ยืนยันแล้ว** หรือ **ต้องดำเนินการ**",
    ],
    action: "ตรวจสอบการชำระเงิน",
  },
  {
    ...en[26],
    title: "หารหัสนักเรียนของฉันได้ที่ไหน?",
    summary: "รหัสนักเรียนจะได้รับตอนที่สร้างโปรไฟล์เสร็จ",
    steps: [
      "รหัสนักเรียนจะแสดงทันทีหลังเลือก **สร้างโปรไฟล์นักเรียน**",
      "เลือก **คัดลอกรหัส** แล้วเก็บไว้ให้ดี รูปแบบเช่น RSK-6901",
      "หากทำหาย ให้เปิด **ติดต่อเรา** แล้วสอบถามโดโจ",
    ],
    action: "สร้างโปรไฟล์นักเรียน",
  },
  {
    ...en[27],
    title: "หลังสร้างโปรไฟล์แล้วจะเกิดอะไรขึ้น?",
    summary: "โปรไฟล์ใช้งานได้ทันทีระหว่างรออาจารย์ตรวจสอบ",
    steps: [
      "หลังเลือก **สร้างโปรไฟล์นักเรียน** คุณใช้โปรไฟล์ได้ทันที",
      "สถานะจะเป็น **รอผู้ดูแลตรวจสอบ** จนกว่าอาจารย์จะตรวจสอบเสร็จ",
      "หากมีการแก้ไขรหัสนักเรียน รหัสเดิมของคุณยังเปิดโปรไฟล์เดียวกันได้",
    ],
    action: "สร้างโปรไฟล์นักเรียน",
  },
  {
    ...en[28],
    title: "เพิ่มรูปในโปรไฟล์อย่างไร?",
    summary: "ใส่รูปประจำตัวลงในพาสปอร์ตนักเรียน",
    steps: [
      "ในแบบฟอร์มโปรไฟล์ใหม่ ให้เลือก **เลือกรูปโปรไฟล์**",
      "หากต้องการเปลี่ยนภายหลัง ให้เปิด **พาสปอร์ตของฉัน** ค้นหาประวัติ แล้วเลือก **Change profile photo**",
      "ใช้รูปหน้าตรงที่ชัดเจน ไฟล์ JPEG, PNG หรือ WebP ขนาดไม่เกิน 8 MB",
    ],
    action: "เปิดพาสปอร์ตของฉัน",
  },
  {
    ...en[29],
    title: "แชร์หรือพิมพ์ประวัติการฝึกอย่างไร?",
    summary: "ส่งประวัติให้โดโจอื่น หรือพิมพ์ออกมาเป็นกระดาษ",
    steps: [
      "เปิด **พาสปอร์ตของฉัน** ในพื้นที่นักเรียน แล้วค้นหาประวัติของคุณ",
      "ไปที่ **คิวอาร์ประวัตินักเรียน** ใต้พาสปอร์ต",
      "เลือก **คัดลอกลิงก์**, **แชร์**, **ดาวน์โหลดคิวอาร์** หรือ **พิมพ์**",
    ],
    action: "เปิดพาสปอร์ตของฉัน",
  },
  {
    ...en[30],
    title: "ตรวจสอบใบสมัครสอบของฉันอย่างไร?",
    summary: "ดูการสอบและผลที่บันทึกไว้ในประวัติของคุณ",
    steps: [
      "เปิด **พาสปอร์ตของฉัน** ในพื้นที่นักเรียน แล้วค้นหาประวัติของคุณ",
      "เปิดแท็บ **ประวัติการสอบ**",
      "การสอบและผลจะแสดงที่นี่หลังอาจารย์บันทึกข้อมูลให้แล้ว",
    ],
    action: "ตรวจสอบการสอบ",
  },
  {
    ...en[31],
    title: "ค่าธรรมเนียมการสอบเข็มขัดเท่าไหร่?",
    summary: "ค่าธรรมเนียมขึ้นอยู่กับระดับที่สมัครสอบ",
    steps: [
      "เปิด **ใบสมัครสอบ** ในพื้นที่นักเรียน",
      "เลือกระดับที่ต้องการสอบ ค่าธรรมเนียมของระดับนั้นจะแสดงอยู่ใต้ช่องเลือก",
      "ค่าธรรมเนียมเดิมจะแสดงอีกครั้งใน **ตรวจทานใบสมัคร** ก่อนส่ง",
    ],
    action: "เปิดใบสมัครสอบ",
  },
  {
    ...en[32],
    title: "ไปเรียนครั้งแรกต้องแต่งตัวและเตรียมอะไร?",
    summary: "ใส่ชุดแบบไหน มาถึงเวลาใด และทำอย่างไรบนเบาะ",
    steps: [
      "เปิด **ชั้นเรียน** จากเมนู แล้วเลือก **คู่มือการเยี่ยมชมครั้งแรก**",
      "สวมกางเกงหลวม ๆ และเสื้อที่เคลื่อนไหวสะดวก ส่วนชุดฝึก (เคโคกิ) ค่อยมีเมื่อคุณพร้อมก็ได้",
      "มาถึงก่อนเวลา ถอดรองเท้าและล้างเท้าก่อนขึ้นเสื่อ",
    ],
    action: "อ่านคู่มือการเยี่ยมชมครั้งแรก",
  },
  {
    ...en[33],
    title: "เด็กเรียนได้ไหม และผู้ปกครองนั่งดูได้หรือไม่?",
    summary: "เด็กเรียนได้ และผู้ปกครองนั่งชมได้ที่ระเบียง",
    steps: [
      "เปิด **ชั้นเรียน** จากเมนู แล้วเลือก **คำถามที่พบบ่อย**",
      "เปิด **ยินดีต้อนรับอายุเท่าไหร่?** และ **ไอคิโดปลอดภัยสำหรับเด็กหรือไม่?**",
      "เปิด **พ่อแม่ดูได้ไหม?** โดโจมีระเบียงพร้อมที่นั่งสำหรับชมการฝึก",
    ],
    action: "อ่านเรื่องชั้นเรียนเด็ก",
  },
  {
    ...en[34],
    title: "ไม่เคยฝึกมาก่อน เริ่มได้ไหม?",
    summary: "ไอคิโดไม่มีการแข่งขัน และรับผู้เริ่มต้นทุกวัย",
    steps: [
      "เลือก **ใครสามารถฝึกได้บ้าง?** ด้านล่างเพื่อเปิดส่วนนั้นของหน้าไอคิโด",
      "อ่านส่วนของเด็ก แล้วอ่านส่วนของผู้ใหญ่",
      "จากนั้นเปิด **ชั้นเรียน** แล้วเลือก **คู่มือการเยี่ยมชมครั้งแรก** เพื่อเตรียมวันแรก",
    ],
    action: "ใครสามารถฝึกได้บ้าง?",
  },
  {
    ...en[35],
    title: "โดโจนี้สร้างขึ้นมาอย่างไร?",
    summary: "ดูเส้นทางของ RenShinKan จากผืนดินว่างเปล่า",
    steps: [
      "เปิด **โดโจของเรา** จากเมนู แล้วเลือก **ประวัติศาสตร์โดโจ**",
      "ชมภาพการก่อสร้างเรียงตามลำดับ",
      "เลือก **แกลเลอรี่ที่มา** ท้ายส่วนนี้เพื่อดูภาพเพิ่มเติม",
    ],
    action: "ดูประวัติศาสตร์โดโจ",
  },
  {
    ...en[36],
    title: "ใครเป็นผู้ก่อตั้งไอคิโด?",
    summary: "อ่านเรื่องของโอเซนเซ ผู้ก่อตั้งไอคิโด",
    steps: [
      "เปิด **ไอคิโด** จากเมนู แล้วเลือก **โอ้อาจารย์**",
      "อ่านเรื่องราวสั้น ๆ ของผู้ก่อตั้ง",
      "หากต้องการเรื่องราวทั้งหมด ให้เลือก **ประวัติความเป็นมาของไอคิโด**",
    ],
    action: "อ่านเรื่องโอเซนเซ",
  },
  {
    ...en[37],
    title: "ดูภาพการสอบเข็มขัดได้ที่ไหน?",
    summary: "ชมภาพถ่ายจากการสอบครั้งที่ผ่านมา",
    steps: [
      "เปิด **ชั้นเรียน** จากเมนู แล้วเลือก **แกลเลอรี่**",
      "เลือกอัลบั้มเพื่อเปิดดูภาพ",
      "สำหรับภาพโดโจและกิจกรรม ให้เปิด **โดโจของเรา** แล้วเลือก **ภาพถ่ายโดโจ**",
    ],
    action: "ดูภาพการสอบ",
  },
  {
    ...en[38],
    title: "หาจดหมายข่าวฉบับเก่าอย่างไร?",
    summary: "ค้นคลังจดหมายข่าวด้วยคำค้น หมวดหมู่ หรือปี",
    steps: [
      "เปิด **จดหมายข่าว** จากเมนู แล้วเลื่อนไปที่ **All newsletters**",
      "พิมพ์คำค้นใน **Search newsletters** หรือเลือก **Category** หรือ **Year**",
      "เลือก **Clear filters** เพื่อเริ่มค้นใหม่",
    ],
    action: "ค้นคลังจดหมายข่าว",
  },
  {
    ...en[39],
    title: "ข้อมูลส่วนตัวของฉันถูกเก็บเป็นความลับหรือไม่?",
    summary: "เว็บไซต์ดูแลชื่อ รหัสนักเรียน และหลักฐานการชำระเงินอย่างไร",
    steps: [
      "**ชื่อนักเรียน** และ **รหัสนักเรียน** ถูกส่งอย่างปลอดภัยและไม่ปรากฏใน URL ของหน้า",
      "ลิงก์สาธารณะไม่อนุญาตให้แก้ไข และไม่เปิดเผยคำตอบในใบสมัครหรือรายละเอียดการชำระเงิน",
      "หลักฐานการชำระเงินถูกเก็บเป็นข้อมูลส่วนตัว หากมีคำถามอื่น ให้เปิด **ติดต่อเรา**",
    ],
    action: "ติดต่อโดโจ",
  },
];

const ja: Topic[] = [
  {
    ...en[0],
    title: "新しい会員プロフィールを作るには？",
    summary: "RenShinKanの確認用にプロフィールを申請します。",
    steps: [
      "会員ページで **新規プロフィール** を開きます。",
      "会員情報を入力し、正しい道場を選びます。",
      "**確認して作成** の内容を確かめ、**学生プロフィールを作成** を選びます。",
    ],
    action: "プロフィールを作成",
  },
  {
    ...en[1],
    title: "審査申請を記入するには？",
    summary: "受付中の審査に申請します。",
    steps: [
      "会員ページで **審査申請** を開きます。",
      "**会員ID** と必須項目をすべて入力します。",
      "**すべての回答を確認** を選び、内容を確かめてから申請を送信し、表示された費用を支払います。",
    ],
    action: "審査申請を開く",
  },
  {
    ...en[2],
    title: "会員パスポートを見るには？",
    summary: "非公開の会員パスポートを開きます。",
    steps: [
      "会員ページで **マイパスポート** を開きます。",
      "**会員名** と **会員ID** を入力します。",
      "**記録を検索** を選び、パスポートのタブを使います。",
    ],
    action: "パスポートを検索",
  },
  {
    ...en[3],
    title: "月会費を支払うには？",
    summary: "月会費を支払い、証明を送信します。",
    steps: [
      "メニューから **サポート** を開き、会費フォームへ進みます。",
      "**道場月会費** を選び、支払いに含まれる会員をすべて入力します。",
      "PromptPayのQRへ進み、表示された金額を支払い、証明をアップロードします。",
    ],
    action: "月会費を支払う",
  },
  {
    ...en[4],
    title: "AAT年会費を支払うには？",
    summary: "番号がない場合はAAT登録後に年会費を送信します。",
    steps: [
      "**マイパスポート** を開き、**支払い** タブを確認します。",
      "AAT番号がない場合は、そこに表示される登録リンクを先に使います。",
      "会費フォームで **AAT年会費** を選び、表示された金額を支払い、鮮明な証明をアップロードします。",
    ],
    action: "会員記録を開く",
  },
  {
    ...en[5],
    title: "道場へ連絡するには？",
    summary: "質問や見学希望を送ります。",
    steps: [
      "メニューから **お問い合わせ** を開きます。",
      "希望する連絡方法を選びます。",
      "名前と簡潔なメッセージを送ります。",
    ],
    action: "道場へ連絡",
  },
  {
    ...en[6],
    title: "道場へ寄付するには？",
    summary: "地域道場を一回の寄付で支援します。",
    steps: [
      "メニューから **サポート** を開き、**寄付** の項目へ進みます。",
      "支払い案内を読むかPromptPayについて道場へ連絡します。",
      "寄付後、支払い確認を保管します。",
    ],
    action: "寄付案内を見る",
  },
  {
    ...en[7],
    title: "道場ニュースレターを読むには？",
    summary: "最新号と過去号を読みます。",
    steps: [
      "メニューまたはホームから **ニュースレター** を開きます。",
      "読みたい号の **ニュースレターを読む** を選びます。",
      "アーカイブの絞り込みで過去号を表示します。",
    ],
    action: "ニュースレターを読む",
  },
  {
    ...en[8],
    title: "メールでニュースレターを受け取るには？",
    summary: "道場の更新をメール購読します。",
    steps: [
      "メニューから **ニュースレター** を開き、登録欄までスクロールします。",
      "**登録フォームを開く** を選び、メールアドレスを入力します。",
      "送信し、確認案内に従います。",
    ],
    action: "メールで受け取る",
  },
  {
    ...en[9],
    title: "稽古時間を申請する方法",
    summary: "現在の合計に含まれていない稽古時間を先生に確認してもらいます。",
    steps: [
      "会員ページで **マイパスポート** を開き、自分の記録を表示します。",
      "パスポートの下にある **稽古時間の追加申請** へ進みます。",
      "稽古日、時間数、内容を入力し、**確認のために送信** を選びます。承認された時間はパスポートに反映されます。",
    ],
    action: "稽古時間の確認を申請",
  },
  {
    ...en[10],
    title: "入門して稽古を始めるには？",
    summary: "まず見学し、そのあとRenShinKanで稽古を始めます。",
    steps: [
      "メニューから **クラス** を開き、**はじめての見学ガイド** を選びます。",
      "初日の流れと持ち物を読みます。",
      "**訪問について質問する** を選び、見学したい日を伝えます。",
    ],
    action: "見学ガイドを見る",
  },
  {
    ...en[11],
    title: "稽古はいつありますか？",
    summary: "毎週の稽古時間と到着の目安を確認します。",
    steps: [
      "メニューから **クラス** を開き、**授業スケジュール** を選びます。",
      "各回の曜日と時間を確認します。",
      "時間の下の注意書きを読み、早めに来て道場の準備を手伝います。",
    ],
    action: "稽古時間を見る",
  },
  {
    ...en[12],
    title: "審査と帯の段級はどう決まりますか？",
    summary: "帯の段級と次の審査のお知らせを確認します。",
    steps: [
      "メニューから **クラス** を開き、**ベルト試験** を選びます。",
      "お知らせと帯の一覧を読みます。",
      "紙の申込書が必要なら **PDF申込書をダウンロード** を選びます。",
    ],
    action: "帯の段級を見る",
  },
  {
    ...en[13],
    title: "よくある質問の答えはどこにありますか？",
    summary: "初めての稽古の前によく聞かれる質問を読みます。",
    steps: [
      "メニューから **クラス** を開き、**よくある質問** を選びます。",
      "質問を選ぶと答えが開きます。",
      "答えが見つからないときは **お問い合わせ** を開きます。",
    ],
    action: "よくある質問を読む",
  },
  {
    ...en[14],
    title: "道場の写真はどこで見られますか？",
    summary: "道場、稽古、行事の写真を見ます。",
    steps: [
      "メニューから **私たちの道場** を開き、**道場の写真** を選びます。",
      "道場内、敷地、集合写真を順に見ます。",
      "行事の写真は **コミュニティ** の **過去のイベント** にあります。",
    ],
    action: "道場の写真を見る",
  },
  {
    ...en[15],
    title: "道場の行事や協力団体について読むには？",
    summary: "過去の行事、財団、大学のクラブを見ます。",
    steps: [
      "メニューから **コミュニティ** を開き、**過去のイベント** を選びます。",
      "行事のアルバムと日付を見ます。",
      "そのまま **Peace Culture Foundation** と **Chiang Mai CMU** へ進みます。",
    ],
    action: "地域の活動を見る",
  },
  {
    ...en[16],
    title: "講習会やセミナーを探すには？",
    summary: "道場の講習会と新しい日程の案内を見ます。",
    steps: [
      "下の **講習会を見る** を選び、講習会のページを開きます。",
      "各講習会のカードで内容を読みます。",
      "新しい日程は **道場の最新情報を見る** で確認します。",
    ],
    action: "講習会を見る",
  },
  {
    ...en[17],
    title: "道場の書類やPDFを入手するには？",
    summary: "正式な書式と審査資料を開きます。",
    steps: [
      "メニューから **サポート** を開き、**ダウンロード** を選びます。",
      "必要な書式を一覧から探します。",
      "**Open or download PDF** を選びます。",
    ],
    action: "ダウンロードを開く",
  },
  {
    ...en[18],
    title: "道場はどこにありますか？",
    summary: "道場の住所を確認し、地図を開きます。",
    steps: [
      "メニューから **私たちの道場** を開き、**場所** を選びます。",
      "道場の住所を読みます。",
      "道順は **地図を開く** で確認します。",
    ],
    action: "道場を探す",
  },
  {
    ...en[19],
    title: "誰が稽古を教えていますか？",
    summary: "RenShinKanの先生方の紹介を読みます。",
    steps: [
      "メニューから **私たちの道場** を開き、**講師** を選びます。",
      "先生ごとの短い紹介を読みます。",
      "さらに質問があれば **お問い合わせ** を開きます。",
    ],
    action: "講師を知る",
  },
  {
    ...en[20],
    title: "合気道とは何ですか？",
    summary: "合気道とその歴史の短い紹介を読みます。",
    steps: [
      "メニューから **合気道** を開き、**合気道とは** を選びます。",
      "紹介文を読み、次に歴史の項目を読みます。",
      "初心者の質問は **クラス** の **よくある質問** にあります。",
    ],
    action: "合気道について読む",
  },
  {
    ...en[21],
    title: "他の言語でこのサイトを読むには？",
    summary: "サイトの言語はいつでも変えられます。",
    steps: [
      "各ページ上部の言語ボタンを探します。",
      "**English**、**ไทย**、**日本語**、**中文** から選びます。",
      "読んでいるページがそのまま新しい言語で表示されます。",
    ],
    action: "ホームを開く",
  },
  {
    ...en[22],
    title: "支払いの証明を送るには？",
    summary: "支払明細をアップロードすると道場が確認できます。",
    steps: [
      "支払い後もそのページに残り、**支払証明をアップロード** を探します。",
      "**支払証明ファイルを選択** を選び、明細の写真かPDFを選びます。",
      "**選択したファイルをアップロード** を選びます。先生が確認し、支払い状況を更新します。",
    ],
    action: "支払証明をアップロード",
  },
  {
    ...en[23],
    title: "複数の会員分をまとめて支払うには？",
    summary: "兄弟姉妹など複数の会員分を一度の支払いにまとめます。",
    steps: [
      "メニューから **サポート** を開き、**この支払いの対象者** を探します。",
      "**生徒を追加** を選び、各人の **生徒ID** と名前を入力します。",
      "**支払合計** を確認し、PromptPayのQRへ進んでその金額を支払います。",
    ],
    action: "複数人分を支払う",
  },
  {
    ...en[24],
    title: "月会費はいくらですか？",
    summary: "支払う前に金額を確認できます。",
    steps: [
      "メニューから **サポート** を開き、**支払う会費を選んでください** を読みます。",
      "**道場月会費** か **AAT年会費** を選ぶと、それぞれの金額が表示されます。",
      "**支払合計** に、追加したすべての会員分の合計が表示されます。",
    ],
    action: "金額を見る",
  },
  {
    ...en[25],
    title: "支払いが受理されたか確認するには？",
    summary: "道場が支払いを確認済みかどうかを見ます。",
    steps: [
      "会員ページで **マイパスポート** を開き、自分の記録を表示します。",
      "**会費** タブを開きます。",
      "各支払いに **審査中**、**確認済み**、**対応が必要** のいずれかが表示されます。",
    ],
    action: "支払いを確認",
  },
  {
    ...en[26],
    title: "会員IDはどこで分かりますか？",
    summary: "会員IDはプロフィール作成時に発行されます。",
    steps: [
      "**生徒プロフィールを作成** を選ぶと、すぐに会員IDが表示されます。",
      "**IDをコピー** を選び、安全な場所に保存します。RSK-6901のような形式です。",
      "分からなくなったら **お問い合わせ** を開いて道場に尋ねてください。",
    ],
    action: "プロフィールを作成",
  },
  {
    ...en[27],
    title: "プロフィール作成後はどうなりますか？",
    summary: "先生が確認する間もプロフィールはすぐ使えます。",
    steps: [
      "**生徒プロフィールを作成** を選ぶと、そのまま使い始められます。",
      "先生が確認するまで、状態は **管理者確認待ち** のままです。",
      "会員IDが修正されても、最初のIDで同じプロフィールを開けます。",
    ],
    action: "プロフィールを作成",
  },
  {
    ...en[28],
    title: "プロフィールに写真を入れるには？",
    summary: "会員パスポートに顔写真を載せます。",
    steps: [
      "新規プロフィールの入力欄で **プロフィール写真を選択** を選びます。",
      "後で変えるときは **マイパスポート** を開いて記録を表示し、**Change profile photo** を選びます。",
      "はっきりした顔写真を使います。JPEG、PNG、WebPで8MBまでです。",
    ],
    action: "マイパスポートを開く",
  },
  {
    ...en[29],
    title: "稽古記録を共有・印刷するには？",
    summary: "他の道場へ送ったり、紙に印刷したりできます。",
    steps: [
      "会員ページで **マイパスポート** を開き、自分の記録を表示します。",
      "パスポートの下の **生徒記録QR** へ進みます。",
      "**リンクをコピー**、**共有**、**QRをダウンロード**、**印刷** から選びます。",
    ],
    action: "マイパスポートを開く",
  },
  {
    ...en[30],
    title: "審査申請を確認するには？",
    summary: "記録済みの審査と結果を確認します。",
    steps: [
      "会員ページで **マイパスポート** を開き、自分の記録を表示します。",
      "**審査履歴** タブを開きます。",
      "審査と結果は、先生が入力したあとここに表示されます。",
    ],
    action: "審査を確認",
  },
  {
    ...en[31],
    title: "審査の費用はいくらですか？",
    summary: "費用は申請する級によって変わります。",
    steps: [
      "会員ページで **審査申請** を開きます。",
      "受審したい級を選ぶと、その級の費用がすぐ下に表示されます。",
      "提出前の **申請内容を確認** にも同じ費用が表示されます。",
    ],
    action: "審査申請を開く",
  },
  {
    ...en[32],
    title: "初回の稽古には何を着て、何を持って行きますか？",
    summary: "服装、到着の目安、畳の上での作法をまとめています。",
    steps: [
      "メニューから **クラス** を開き、**はじめての見学ガイド** を選びます。",
      "ゆったりしたズボンと動きやすいシャツでお越しください。道着は気持ちが整ってからで大丈夫です。",
      "早めに来て、畳に上がる前に靴を脱ぎ、足を洗ってください。",
    ],
    action: "見学ガイドを読む",
  },
  {
    ...en[33],
    title: "子どもも稽古できますか。保護者は見学できますか？",
    summary: "子どもも歓迎で、保護者は見学デッキから見られます。",
    steps: [
      "メニューから **クラス** を開き、**よくある質問** を選びます。",
      "**何歳まで歓迎ですか？** と **合気道は子供にとって安全ですか?** を開きます。",
      "**保護者の方も見ていただけますか？** を開きます。道場には座席のある見学デッキがあります。",
    ],
    action: "子どものクラスを読む",
  },
  {
    ...en[34],
    title: "まったくの初心者でも始められますか？",
    summary: "合気道に試合はなく、年齢を問わず初心者を歓迎します。",
    steps: [
      "下の **誰が練習できるの？** を選び、合気道ページのその項目を開きます。",
      "子どもの項目、次に大人の項目を読みます。",
      "そのあと **クラス** の **はじめての見学ガイド** で初日の準備をします。",
    ],
    action: "誰が練習できるの？",
  },
  {
    ...en[35],
    title: "道場はどのように建てられましたか？",
    summary: "更地からのRenShinKanの歩みをたどります。",
    steps: [
      "メニューから **私たちの道場** を開き、**道場の歴史** を選びます。",
      "建設の写真を順に見ます。",
      "最後の **ソースギャラリー** を選ぶと写真がさらに見られます。",
    ],
    action: "道場の歴史を見る",
  },
  {
    ...en[36],
    title: "合気道を創始したのは誰ですか？",
    summary: "合気道の創始者、開祖について読みます。",
    steps: [
      "メニューから **合気道** を開き、**ああ先生** を選びます。",
      "創始者の短い物語を読みます。",
      "全体の流れは **合気道の歴史** で読めます。",
    ],
    action: "開祖について読む",
  },
  {
    ...en[37],
    title: "審査の写真はどこで見られますか？",
    summary: "これまでの審査の写真を見ます。",
    steps: [
      "メニューから **クラス** を開き、**ギャラリー** を選びます。",
      "アルバムを選ぶと写真が開きます。",
      "道場や行事の写真は **私たちの道場** の **道場の写真** にあります。",
    ],
    action: "審査の写真を見る",
  },
  {
    ...en[38],
    title: "古いニュースレターを探すには？",
    summary: "語句、分類、年でアーカイブを検索します。",
    steps: [
      "メニューから **ニュースレター** を開き、**All newsletters** までスクロールします。",
      "**Search newsletters** に語句を入力するか、**Category** や **Year** を選びます。",
      "**Clear filters** を選ぶと最初からやり直せます。",
    ],
    action: "アーカイブを検索",
  },
  {
    ...en[39],
    title: "個人情報は守られますか？",
    summary: "氏名、会員ID、支払証明の扱いについて説明します。",
    steps: [
      "**会員名** と **会員ID** は安全に送信され、ページURLには含まれません。",
      "共有リンクから編集はできず、申請回答や支払い情報も表示されません。",
      "支払証明は非公開の記録として保管されます。他のご質問は **お問い合わせ** からどうぞ。",
    ],
    action: "道場へ連絡",
  },
];

const zh: Topic[] = [
  {
    ...en[0],
    title: "如何创建新学员资料？",
    summary: "提交资料供 RenShinKan 审核。",
    steps: [
      "在学员工作区打开 **新资料**。",
      "填写学员信息并选择正确的道场。",
      "核对 **检查并创建** 的摘要，然后选择 **创建学员资料**。",
    ],
    action: "创建学员资料",
  },
  {
    ...en[1],
    title: "如何填写考试申请？",
    summary: "申请当前开放的考试。",
    steps: [
      "在学员工作区打开 **考试申请**。",
      "填写 **学员编号** 和所有必填问题。",
      "选择 **检查全部答案**，核对摘要后提交申请并支付显示的费用。",
    ],
    action: "打开考试申请",
  },
  {
    ...en[2],
    title: "如何查看学员护照？",
    summary: "打开私密学员护照。",
    steps: [
      "在学员工作区打开 **我的护照**。",
      "填写 **学员姓名** 和 **学员编号**。",
      "选择 **查找我的记录**，然后使用护照标签页。",
    ],
    action: "查找我的护照",
  },
  {
    ...en[3],
    title: "如何支付每月道场会费？",
    summary: "支付并提交每月会费证明。",
    steps: [
      "从菜单打开 **支持**，进入缴费表单。",
      "选择 **道场月费**，填写本次付款涵盖的所有学员。",
      "继续到 PromptPay 二维码，按显示金额付款后上传付款证明。",
    ],
    action: "支付每月会费",
  },
  {
    ...en[4],
    title: "如何支付 AAT 年费？",
    summary: "没有 AAT 编号时先注册，再提交年费。",
    steps: [
      "打开 **我的护照**，查看 **缴费** 标签页。",
      "如没有 AAT 编号，先使用其中显示的 AAT 注册链接。",
      "在缴费表单选择 **AAT 年度缴费**，按显示金额付款并上传清晰证明。",
    ],
    action: "打开学员记录",
  },
  {
    ...en[5],
    title: "如何联系道场？",
    summary: "向 RenShinKan 发送问题或参观咨询。",
    steps: [
      "从菜单打开 **联系我们**。",
      "选择合适的联系方法。",
      "填写姓名和简短清楚的消息。",
    ],
    action: "联系道场",
  },
  {
    ...en[6],
    title: "如何向道场捐款？",
    summary: "通过一次性捐款支持社区道场。",
    steps: [
      "从菜单打开 **支持**，进入 **捐款** 部分。",
      "阅读付款信息或联系道场获取 PromptPay。",
      "完成捐款并保留付款确认。",
    ],
    action: "查看捐款信息",
  },
  {
    ...en[7],
    title: "如何阅读道场通讯？",
    summary: "阅读最新通讯并浏览存档。",
    steps: [
      "从菜单或主页打开 **时事通讯**。",
      "选择想看的那一期的 **阅读通讯**。",
      "使用存档筛选查看旧通讯。",
    ],
    action: "阅读通讯",
  },
  {
    ...en[8],
    title: "如何通过电子邮件接收通讯？",
    summary: "订阅道场发布的更新。",
    steps: [
      "从菜单打开 **时事通讯**，滚动到订阅部分。",
      "选择 **打开订阅表单**，输入电子邮件地址。",
      "提交并按确认提示操作。",
    ],
    action: "通过邮件接收更新",
  },
  {
    ...en[9],
    title: "如何申请训练小时数",
    summary: "请老师核实尚未计入当前总数的训练时间。",
    steps: [
      "在学员工作区打开 **我的护照**，找到自己的记录。",
      "前往护照下方的 **提交额外训练小时数**。",
      "填写训练日期、小时数和详情，然后选择 **提交审核**。通过的小时数会显示在护照中。",
    ],
    action: "申请核实训练小时数",
  },
  {
    ...en[10],
    title: "如何加入道场并开始训练？",
    summary: "先来观摩一节课，再开始在 RenShinKan 训练。",
    steps: [
      "从菜单打开 **课程**，再选择 **初次参观指南**。",
      "阅读第一天的流程和需要带的物品。",
      "选择 **询问参观事宜**，告诉道场你想来的时间。",
    ],
    action: "查看初次参观指南",
  },
  {
    ...en[11],
    title: "课程在什么时间？",
    summary: "查看每周课程时间和到场时间。",
    steps: [
      "从菜单打开 **课程**，再选择 **课程表**。",
      "查看每节课的日期和时间。",
      "阅读时间表下方的说明，并提早到场帮忙准备道场。",
    ],
    action: "查看课程时间",
  },
  {
    ...en[12],
    title: "腰带考试和级别是怎样的？",
    summary: "查看腰带级别和下一次考试公告。",
    steps: [
      "从菜单打开 **课程**，再选择 **腰带考试**。",
      "阅读公告和腰带级别图。",
      "如需纸质申请表，选择 **下载 PDF 表格**。",
    ],
    action: "查看腰带级别",
  },
  {
    ...en[13],
    title: "在哪里找到常见问题的答案？",
    summary: "阅读第一次上课前最常问的问题。",
    steps: [
      "从菜单打开 **课程**，再选择 **常见问题解答**。",
      "点选问题即可展开答案。",
      "如果没有你的问题，请打开 **联系我们**。",
    ],
    action: "阅读常见问题",
  },
  {
    ...en[14],
    title: "在哪里可以看道场照片？",
    summary: "浏览道场、课堂和活动照片。",
    steps: [
      "从菜单打开 **我们的道场**，再选择 **道场照片**。",
      "依次浏览道场内、场地和集体照片。",
      "活动照片请打开 **社区** 的 **过去的活动**。",
    ],
    action: "查看道场照片",
  },
  {
    ...en[15],
    title: "在哪里了解道场活动和合作伙伴？",
    summary: "查看过去的活动、基金会和大学社团。",
    steps: [
      "从菜单打开 **社区**，再选择 **过去的活动**。",
      "浏览活动相册和日期。",
      "继续查看 **Peace Culture Foundation** 和 **Chiang Mai University**。",
    ],
    action: "查看社区活动",
  },
  {
    ...en[16],
    title: "如何查找工作坊和研习会？",
    summary: "查看道场工作坊以及新日期发布的地方。",
    steps: [
      "选择下方的 **查看工作坊** 打开工作坊页面。",
      "阅读每个工作坊卡片的内容。",
      "选择 **查看道场更新** 了解新日期。",
    ],
    action: "查看工作坊",
  },
  {
    ...en[17],
    title: "如何获取道场表格和 PDF 文件？",
    summary: "打开正式表格和考试参考资料。",
    steps: [
      "从菜单打开 **支持**，再选择 **下载**。",
      "在列表中找到需要的表格或资料。",
      "选择 **Open or download PDF**。",
    ],
    action: "打开下载页",
  },
  {
    ...en[18],
    title: "道场在哪里？怎么去？",
    summary: "查看道场地址并打开地图。",
    steps: [
      "从菜单打开 **我们的道场**，再选择 **地点**。",
      "阅读道场地址。",
      "选择 **打开地图** 查看路线。",
    ],
    action: "找到道场",
  },
  {
    ...en[19],
    title: "谁在教课？",
    summary: "阅读 RenShinKan 老师的简介。",
    steps: [
      "从菜单打开 **我们的道场**，再选择 **导师**。",
      "阅读每位老师的简短介绍。",
      "还有问题请打开 **联系我们**。",
    ],
    action: "认识导师",
  },
  {
    ...en[20],
    title: "什么是合气道？",
    summary: "阅读合气道及其历史的简短介绍。",
    steps: [
      "从菜单打开 **合气道**，再选择 **什么是合气道**。",
      "先读介绍，再读历史部分。",
      "初学者的问题请看 **课程** 的 **常见问题解答**。",
    ],
    action: "了解合气道",
  },
  {
    ...en[21],
    title: "如何用其他语言阅读本网站？",
    summary: "随时可以更改网站语言。",
    steps: [
      "在每页顶部找到语言按钮。",
      "选择 **English**、**ไทย**、**日本語** 或 **中文**。",
      "正在阅读的页面会以新语言显示。",
    ],
    action: "打开首页",
  },
  {
    ...en[22],
    title: "如何提交付款凭证？",
    summary: "上传付款单据，道场才能确认这笔付款。",
    steps: [
      "付款后留在同一页面，找到 **上传付款凭证**。",
      "选择 **选择付款凭证文件**，再选单据的照片或 PDF。",
      "选择 **上传所选文件**。老师会查看并更新付款状态。",
    ],
    action: "上传付款凭证",
  },
  {
    ...en[23],
    title: "如何一次为多名学员付款？",
    summary: "把几名学员，例如兄弟姐妹，合并到一次付款。",
    steps: [
      "从菜单打开 **支持**，找到 **本次付款包括哪些学员？**",
      "选择 **添加一名学员**，填写每人的 **学员编号** 和姓名。",
      "核对 **应付总额**，继续前往 PromptPay 二维码并支付该金额。",
    ],
    action: "为多名学员付款",
  },
  {
    ...en[24],
    title: "每月会费是多少？",
    summary: "付款之前先看清楚金额。",
    steps: [
      "从菜单打开 **支持**，阅读 **您想支付哪项费用？**",
      "选择 **道场月费** 或 **AAT 年度缴费**，即可看到各自的金额。",
      "**应付总额** 会显示你添加的所有学员的合计金额。",
    ],
    action: "查看金额",
  },
  {
    ...en[25],
    title: "如何确认付款是否已被接受？",
    summary: "查看道场是否已确认你的付款。",
    steps: [
      "在学员工作区打开 **我的护照**，找到自己的记录。",
      "打开 **会费记录** 标签页。",
      "每笔付款会显示 **审核中**、**已验证** 或 **需要处理**。",
    ],
    action: "查看我的付款",
  },
  {
    ...en[26],
    title: "在哪里能找到我的学员编号？",
    summary: "创建资料时就会得到学员编号。",
    steps: [
      "选择 **创建学员资料** 后，学员编号会立刻显示。",
      "选择 **复制编号** 并妥善保存。格式类似 RSK-6901。",
      "如果丢失，请打开 **联系我们** 询问道场。",
    ],
    action: "创建学员资料",
  },
  {
    ...en[27],
    title: "创建资料之后会怎样？",
    summary: "老师审核期间，资料已可立即使用。",
    steps: [
      "选择 **创建学员资料** 后，资料马上就能使用。",
      "在老师审核完成前，状态一直是 **等待管理员审核**。",
      "即使学员编号被更正，最初的编号仍能打开同一份资料。",
    ],
    action: "创建学员资料",
  },
  {
    ...en[28],
    title: "如何为资料添加照片？",
    summary: "为学员护照加上一张正面照。",
    steps: [
      "在新资料表单中选择 **选择资料照片**。",
      "以后想更换，请打开 **我的护照**，找到记录，再选择 **Change profile photo**。",
      "使用清晰的正面照。JPEG、PNG 或 WebP，不超过 8 MB。",
    ],
    action: "打开我的护照",
  },
  {
    ...en[29],
    title: "如何分享或打印训练记录？",
    summary: "把记录发给其他道场，或打印在纸上。",
    steps: [
      "在学员工作区打开 **我的护照**，找到自己的记录。",
      "前往护照下方的 **学员记录二维码**。",
      "选择 **复制链接**、**分享**、**下载二维码** 或 **打印**。",
    ],
    action: "打开我的护照",
  },
  {
    ...en[30],
    title: "如何查看我的考试申请？",
    summary: "查看记录中已有的考试和成绩。",
    steps: [
      "在学员工作区打开 **我的护照**，找到自己的记录。",
      "打开 **考级记录** 标签页。",
      "老师录入后，考试和成绩就会显示在这里。",
    ],
    action: "查看我的考试",
  },
  {
    ...en[31],
    title: "腰带考试要多少钱？",
    summary: "费用取决于你申请的级别。",
    steps: [
      "在学员工作区打开 **考试申请**。",
      "选择想要报考的级别，该级别的费用会显示在下方。",
      "提交前的 **检查您的申请** 页面也会再次显示同一笔费用。",
    ],
    action: "打开考试申请",
  },
  {
    ...en[32],
    title: "第一次上课该穿什么、带什么？",
    summary: "穿着、到场时间，以及在垫子上的做法。",
    steps: [
      "从菜单打开 **课程**，再选择 **初次参观指南**。",
      "穿宽松的裤子和方便活动的上衣即可。等您准备好了，再添置道服也不迟。",
      "提早到场，上垫子前请脱鞋，并把脚洗干净。",
    ],
    action: "阅读初次参观指南",
  },
  {
    ...en[33],
    title: "孩子可以练习吗？家长能看吗？",
    summary: "欢迎孩子参加，家长可在观看台就座。",
    steps: [
      "从菜单打开 **课程**，再选择 **常见问题解答**。",
      "打开 **欢迎哪些年龄的人？** 和 **合气道对孩子安全吗？**",
      "打开 **家长可以观看吗？** 道场设有带座位的观看台。",
    ],
    action: "了解儿童课程",
  },
  {
    ...en[34],
    title: "完全没练过也能开始吗？",
    summary: "合气道没有比赛，欢迎任何年龄的初学者。",
    steps: [
      "选择下方的 **谁可以练习？** 打开合气道页面的该部分。",
      "先读关于孩子的内容，再读关于成人的内容。",
      "然后打开 **课程** 的 **初次参观指南**，安排你的第一天。",
    ],
    action: "谁可以练习？",
  },
  {
    ...en[35],
    title: "道场是怎么建起来的？",
    summary: "看看 RenShinKan 如何从一片空地建成。",
    steps: [
      "从菜单打开 **我们的道场**，再选择 **道场历史**。",
      "按顺序浏览建造过程的照片。",
      "选择末尾的 **来源画廊** 可以看到更多照片。",
    ],
    action: "查看道场历史",
  },
  {
    ...en[36],
    title: "合气道是谁创立的？",
    summary: "阅读合气道创始人 O Sensei 的故事。",
    steps: [
      "从菜单打开 **合气道**，再选择 **O Sensei**。",
      "阅读创始人的简短故事。",
      "想了解完整脉络，请选择 **合气道的历史**。",
    ],
    action: "了解 O Sensei",
  },
  {
    ...en[37],
    title: "在哪里可以看腰带考试的照片？",
    summary: "浏览历次考级的照片。",
    steps: [
      "从菜单打开 **课程**，再选择 **画廊**。",
      "选择一个相册即可打开照片。",
      "道场和活动照片请打开 **我们的道场** 的 **道场照片**。",
    ],
    action: "查看考试照片",
  },
  {
    ...en[38],
    title: "如何找到过去的通讯？",
    summary: "用关键词、分类或年份搜索通讯存档。",
    steps: [
      "从菜单打开 **时事通讯**，滚动到 **All newsletters**。",
      "在 **Search newsletters** 输入关键词，或选择 **Category** 或 **Year**。",
      "选择 **Clear filters** 可以重新开始。",
    ],
    action: "搜索存档",
  },
  {
    ...en[39],
    title: "我的个人信息会被保密吗？",
    summary: "说明网站如何处理姓名、编号和付款凭证。",
    steps: [
      "**学员姓名** 和 **学员编号** 会安全传输，绝不会写入页面网址。",
      "公开链接不能用于编辑，也不会显示申请答案或付款详情。",
      "付款凭证作为私密记录保存。其他问题请打开 **联系我们**。",
    ],
    action: "联系道场",
  },
];

export function getPublicHelpCatalog(locale: Language): HelpCatalog {
  const topics =
    locale === "th" ? th : locale === "ja" ? ja : locale === "zh-CN" ? zh : en;
  return {
    audience: "public",
    locale,
    ui: helpUi(locale),
    articles: buildArticles("public", locale, topics.map(article)),
  };
}
