/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=../wrangler.audit-cleanup.jsonc --env-file=serverless/.env.types --include-runtime=false audit-cleanup-env.d.ts` (hash: c568d9b3337f9ce834443b55eb5fa669)
interface __BaseEnv_Env {
	STUDENT_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./audit-cleanup-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
