import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, History, LoaderCircle, LogOut, ReceiptText, Search, X } from "lucide-react";
import { Link } from "react-router-dom";
import { AdminCheckingSession, AdminDojoSelector, AdminLoginFields } from "../components/admin/AdminAccess";
import { adminApi, formatAdminDate } from "../components/admin/adminApi";
import { useAdminSession } from "../components/admin/useAdminSession";

type Membership = {
  id: string; display_name: string; public_student_id: string; dojo_id: string; dojo_name: string; aatDisplay: string;
  aat_number: string | null; aat_last_paid_date: string | null; aat_notes: string;
  membership: { state: "new" | "unpaid" | "current" | "expiring" | "expired"; label: string; dueDate: string | null; days: number | null };
  history: Array<{ id: string; paymentDate: string; renewalDueDate: string; amount: number | null; currency: string; notes: string; recordedBy: string; createdAt: string }>;
};
type Response = { memberships: Membership[]; pagination: { page: number; pageSize: number; total: number; totalPages: number } };

export function AdminMembershipsPage() {
  const session = useAdminSession(); const [rows, setRows] = useState<Membership[]>([]); const [pagination, setPagination] = useState({ page: 1, pageSize: 40, total: 0, totalPages: 1 });
  const [queryInput, setQueryInput] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [dojoId, setDojoId] = useState(""); const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [selected, setSelected] = useState<Membership | null>(null);
  const [payment, setPayment] = useState({ paymentDate: new Date().toISOString().slice(0, 10), aatNumber: "", amount: "", notes: "" }); const [saving, setSaving] = useState(false);
  async function load() {
    if (!session.admin?.selectedDojoId) return; setLoading(true); setError("");
    try { const params = new URLSearchParams({ page: String(page) }); if (query) params.set("query", query); if (status) params.set("status", status); if (dojoId && session.admin.role === "central") params.set("dojoId", dojoId); const body = await adminApi<Response>(`/api/admin/memberships?${params}`); setRows(body.memberships); setPagination(body.pagination); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Membership records could not be loaded."); }
    finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, [session.admin?.selectedDojoId, query, status, dojoId, page]);
  async function markPaid(event: FormEvent) {
    event.preventDefault(); if (!selected) return; setSaving(true); setError("");
    try { await adminApi("/api/admin/memberships", { method: "POST", body: JSON.stringify({ action: "mark_paid", confirmed: true, studentId: selected.id, ...payment }) }); setNotice(`AAT payment recorded for ${selected.display_name}.`); setSelected(null); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "The payment could not be recorded."); }
    finally { setSaving(false); }
  }
  if (!session.checked) return <AdminCheckingSession />;
  if (!session.admin) return <main className="admin-gate"><form onSubmit={session.login}><AdminLoginFields name={session.name} password={session.password} error={session.error} busy={session.busy} setName={session.setName} setPassword={session.setPassword} /></form></main>;
  if (!session.admin.selectedDojoId) return <AdminDojoSelector dojos={session.dojos} admin={session.admin} busyId={session.selecting} error={session.error} onSelect={(id) => void session.selectDojo(id)} />;
  return <section className="container-shell py-10 student-admin">
    <header className="student-admin__header"><div><p className="eyebrow">Annual contribution</p><h1>AAT membership</h1><p>Renewal dates and immutable payment history for the students you are authorized to manage.</p></div><div className="admin-header-actions"><Link className="btn-secondary" to="/admin/students"><ChevronLeft size={16} /> Students</Link><button className="btn-secondary" onClick={() => void session.logout()}><LogOut size={16} /> Sign out</button></div></header>
    {error ? <p className="form-error" role="alert">{error}</p> : null}{notice ? <p className="admin-notice" role="status">{notice}</p> : null}
    <form className="admin-record-filters" onSubmit={(event) => { event.preventDefault(); setPage(1); setQuery(queryInput.trim()); }}><label className="admin-search-wide">Search<div><Search size={17} /><input value={queryInput} onChange={(event) => setQueryInput(event.target.value)} placeholder="Name, Student ID, or AAT number" /><button className="btn-secondary">Search</button></div></label><label>Membership status<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option><option value="new">NEW</option><option value="unpaid">Payment required</option><option value="current">Current</option><option value="expiring">Expiring soon</option><option value="expired">Expired</option></select></label>{session.admin.role === "central" ? <label>Dojo<select value={dojoId} onChange={(event) => { setDojoId(event.target.value); setPage(1); }}><option value="">All dojos</option>{session.dojos.map((dojo) => <option key={dojo.id} value={dojo.id}>{dojo.official_name}</option>)}</select></label> : null}</form>
    <div className="admin-table-scroll"><table className="admin-record-table"><thead><tr><th>Student</th><th>Student ID</th><th>Dojo</th><th>AAT number</th><th>Last paid</th><th>Renewal due</th><th>Status</th><th>History</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><th>{row.display_name}</th><td><code>{row.public_student_id}</code></td><td>{row.dojo_name}</td><td><strong>{row.aatDisplay}</strong></td><td>{row.aat_last_paid_date || "Not yet paid"}</td><td>{row.membership.dueDate || "Unknown"}</td><td><span className={`admin-status ${row.membership.state === "expired" || row.membership.state === "unpaid" ? "is-error" : row.membership.state === "expiring" ? "is-pending" : row.membership.state === "current" ? "is-active" : "is-neutral"}`}>{row.membership.state === "expired" ? <AlertTriangle size={14} /> : row.membership.state === "current" ? <CheckCircle2 size={14} /> : null}{row.membership.label}{row.membership.days != null ? ` · ${Math.abs(row.membership.days)} day${Math.abs(row.membership.days) === 1 ? "" : "s"} ${row.membership.days < 0 ? "overdue" : "remaining"}` : ""}</span></td><td><details><summary><History size={15} /> {row.history.length} payment{row.history.length === 1 ? "" : "s"}</summary><ol>{row.history.map((entry) => <li key={entry.id}><strong>{entry.paymentDate}</strong> · {entry.amount == null ? "Amount not recorded" : `${entry.amount.toLocaleString()} ${entry.currency}`} · by {entry.recordedBy}{entry.notes ? <div>{entry.notes}</div> : null}</li>)}</ol></details></td><td><button className="btn-primary" onClick={() => { setSelected(row); setPayment({ paymentDate: new Date().toISOString().slice(0, 10), aatNumber: row.aat_number || "", amount: "", notes: row.aat_notes || "" }); }}><ReceiptText size={16} /> Mark paid</button></td></tr>)}{!rows.length && !loading ? <tr><td colSpan={9}>No membership records match these filters.</td></tr> : null}</tbody></table></div>
    <footer className="admin-pagination"><span>{pagination.total} records</span><div><button className="btn-secondary" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft size={16} /> Previous</button><span>Page {page} of {pagination.totalPages}</span><button className="btn-secondary" disabled={page >= pagination.totalPages} onClick={() => setPage((value) => value + 1)}>Next <ChevronRight size={16} /></button></div></footer>
    {loading ? <div className="admin-loading-overlay"><LoaderCircle className="spin" /> Loading memberships</div> : null}
    {selected ? <div className="admin-confirm-backdrop"><section className="admin-confirm-dialog" role="dialog" aria-modal="true"><header><div><p className="eyebrow">AAT annual contribution</p><h2>Record payment for {selected.display_name}</h2></div><button aria-label="Close" onClick={() => setSelected(null)}><X /></button></header><form className="admin-bulk-form" onSubmit={markPaid}><label>AAT number (optional)<input value={payment.aatNumber} onChange={(event) => setPayment({ ...payment, aatNumber: event.target.value })} placeholder="Leave blank to keep NEW" /></label><label>Payment date<input type="date" required value={payment.paymentDate} onChange={(event) => setPayment({ ...payment, paymentDate: event.target.value })} /></label><label>Amount in THB (optional)<input type="number" min="0" step="0.01" value={payment.amount} onChange={(event) => setPayment({ ...payment, amount: event.target.value })} /></label><label>Notes<textarea maxLength={2000} value={payment.notes} onChange={(event) => setPayment({ ...payment, notes: event.target.value })} /></label><p className="admin-help">Renewal is normally due one calendar year after this payment. This action adds a new history entry; it does not erase earlier payments.</p><footer><button type="button" className="btn-secondary" onClick={() => setSelected(null)}>Cancel</button><button className="btn-primary" disabled={saving}>{saving ? <LoaderCircle className="spin" size={16} /> : <ReceiptText size={16} />} Confirm payment</button></footer></form></section></div> : null}
  </section>;
}
