import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgePlus, Clock3, GraduationCap, Lock, Printer, QrCode, Search, ShieldCheck, Upload, UserPlus } from "lucide-react";
import { Link } from "react-router-dom";
import QRCodeLib from "qrcode";

type Student = { id: string; public_student_id: string; display_name: string; current_belt: string; belt_color: string; profile_image_url: string | null; profile_image_consent: number; guardian_consent: number; public_visible: number; active: number; share_fields: string; total_hours: number; sharing_active: number };
type Detail = { student: Student; examinations: Array<Record<string, unknown>>; trainingHours: Array<Record<string, unknown>> };
const belts = ["Unranked", "10 Kyu", "9 Kyu", "8 Kyu", "7 Kyu", "6 Kyu", "5 Kyu", "4 Kyu", "3 Kyu", "2 Kyu", "1 Kyu", "SHO Dan-Ho"];
const colors = ["white", "orange", "blue", "green", "brown", "black"];
async function jsonFetch(url: string, options?: RequestInit) { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", ...(options?.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Request failed"); return body; }
async function imageToWebp(file: File) { const bitmap = await createImageBitmap(file); const max = 1000; const scale = Math.min(1, max / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement("canvas"); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale); canvas.getContext("2d")!.drawImage(bitmap, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error("Could not prepare image")), "image/webp", .84)); bitmap.close(); return new File([blob], "profile.webp", { type: "image/webp" }); }

export function AdminStudentsPage() {
  const [checked, setChecked] = useState(false); const [authed, setAuthed] = useState(false); const [password, setPassword] = useState(""); const [students, setStudents] = useState<Student[]>([]); const [selectedId, setSelectedId] = useState(""); const [detail, setDetail] = useState<Detail | null>(null); const [query, setQuery] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [shareUrl, setShareUrl] = useState(""); const [qr, setQr] = useState("");
  const [newStudent, setNewStudent] = useState({ displayName: "", studentId: "", lookupCode: "", currentBelt: "Unranked", beltColor: "white", guardianConsent: false, publicVisible: true });
  const [exam, setExam] = useState({ date: "", belt: "", beltColor: "white", rank: "", examiner: "", publicNotes: "", internalNotes: "", updateCurrentBelt: true });
  const [hours, setHours] = useState({ date: "", periodEnd: "", hours: "", source: "", internalNote: "" });
  const filtered = useMemo(() => students.filter((item) => `${item.display_name} ${item.public_student_id} ${item.current_belt}`.toLowerCase().includes(query.toLowerCase())), [students, query]);
  async function loadStudents() { const body = await jsonFetch("/api/admin/students"); setStudents(body.students); }
  async function loadDetail(id: string) { setSelectedId(id); setShareUrl(""); setQr(""); setDetail(await jsonFetch(`/api/admin/students/${id}`)); }
  useEffect(() => { fetch("/api/admin/session", { cache: "no-store" }).then((response) => { setAuthed(response.ok); setChecked(true); if (response.ok) loadStudents().catch((reason) => setError(reason.message)); }); }, []);
  async function login(event: FormEvent) { event.preventDefault(); setError(""); try { await jsonFetch("/api/admin/login", { method: "POST", body: JSON.stringify({ password }) }); setAuthed(true); await loadStudents(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Sign in failed"); } }
  async function addStudent(event: FormEvent) { event.preventDefault(); setError(""); try { const body = await jsonFetch("/api/admin/students", { method: "POST", body: JSON.stringify(newStudent) }); setNotice(`Student added. Give the private lookup code to the student or guardian through a safe channel: ${body.lookupCode}`); setNewStudent({ displayName: "", studentId: "", lookupCode: "", currentBelt: "Unranked", beltColor: "white", guardianConsent: false, publicVisible: true }); await loadStudents(); await loadDetail(body.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not add student"); } }
  async function saveStudent() { if (!detail) return; const student = detail.student; const shareFields = (() => { try { return JSON.parse(student.share_fields); } catch { return {}; } })(); try { await jsonFetch(`/api/admin/students/${student.id}`, { method: "PUT", body: JSON.stringify({ displayName: student.display_name, currentBelt: student.current_belt, beltColor: student.belt_color, profileImageUrl: student.profile_image_url, profileImageConsent: Boolean(student.profile_image_consent), guardianConsent: Boolean(student.guardian_consent), publicVisible: Boolean(student.public_visible), active: Boolean(student.active), shareFields }) }); setNotice("Student record saved."); await loadStudents(); await loadDetail(student.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save"); } }
  async function addExam(event: FormEvent) { event.preventDefault(); if (!detail) return; try { await jsonFetch(`/api/admin/students/${detail.student.id}/exam`, { method: "POST", body: JSON.stringify(exam) }); setNotice("Belt examination recorded."); setExam({ date: "", belt: "", beltColor: "white", rank: "", examiner: "", publicNotes: "", internalNotes: "", updateCurrentBelt: true }); await loadStudents(); await loadDetail(detail.student.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not record examination"); } }
  async function addHours(event: FormEvent) { event.preventDefault(); if (!detail) return; try { await jsonFetch(`/api/admin/students/${detail.student.id}/hours`, { method: "POST", body: JSON.stringify(hours) }); setNotice("Training hours added."); setHours({ date: "", periodEnd: "", hours: "", source: "", internalNote: "" }); await loadStudents(); await loadDetail(detail.student.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not add hours"); } }
  async function generateShare() { if (!detail) return; const body = await jsonFetch(`/api/admin/students/${detail.student.id}/share`, { method: "POST" }); setShareUrl(body.url); setQr(await QRCodeLib.toDataURL(body.url, { width: 420, margin: 2 })); setNotice("A new share link was generated. Any previous link is now revoked."); await loadStudents(); }
  async function revokeShare() { if (!detail || !confirm("Revoke the current public share link? Printed QR codes will stop working.")) return; await jsonFetch(`/api/admin/students/${detail.student.id}/share`, { method: "DELETE" }); setShareUrl(""); setQr(""); setNotice("Public sharing revoked."); await loadStudents(); }
  async function uploadProfile(file?: File) { if (!file || !detail) return; setError(""); try { const webp = await imageToWebp(file); const form = new FormData(); form.append("file", webp); const response = await fetch("/api/admin/students/upload", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setDetail({ ...detail, student: { ...detail.student, profile_image_url: body.url } }); setNotice("Photo prepared. Confirm consent and save the student record."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not upload image"); } }
  function updateStudent(values: Partial<Student>) { if (detail) setDetail({ ...detail, student: { ...detail.student, ...values } }); }
  if (!checked) return <section className="container-shell admin-loading" aria-live="polite">Checking the secure session…</section>;
  if (!authed) return <section className="container-shell admin-login"><form onSubmit={login}><Lock size={24} /><p className="eyebrow">Admin</p><h1>Student records</h1><label>Password<input className="input-field" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error ? <p className="form-error">{error}</p> : null}<button className="btn-primary">Sign in</button></form></section>;
  return <section className="container-shell student-admin">
    <header className="student-admin__header"><div><Link to="/admin" className="text-link"><ArrowLeft size={16} /> Content administration</Link><p className="eyebrow">Student records</p><h1>Training record desk</h1><p>Add students, record hours and examinations, and control exactly what may be shared.</p></div><div className="admin-stat"><strong>{students.filter((item) => item.active).length}</strong><span>active students</span></div></header>
    {notice ? <p className="admin-notice" role="status"><ShieldCheck size={18} />{notice}</p> : null}{error ? <p className="form-error" role="alert">{error}</p> : null}
    <div className="student-admin__layout">
      <aside className="student-list"><label className="admin-search"><Search size={16} /><span className="sr-only">Search students</span><input placeholder="Search name, ID or belt" value={query} onChange={(event) => setQuery(event.target.value)} /></label><ul>{filtered.map((student) => <li key={student.id}><button className={selectedId === student.id ? "is-active" : ""} onClick={() => loadDetail(student.id)}><span className={`belt-dot belt-dot--${student.belt_color}`} /><span><strong>{student.display_name}</strong><small>{student.public_student_id} · {student.current_belt}</small></span>{student.sharing_active ? <QrCode size={15} aria-label="Sharing active" /> : null}</button></li>)}</ul></aside>
      <main className="student-workspace">
        <details className="admin-workflow" open={!detail}><summary><UserPlus size={20} /> Add a student</summary><form onSubmit={addStudent} className="admin-form-grid"><label>Display and verification name<input value={newStudent.displayName} onChange={(e) => setNewStudent({ ...newStudent, displayName: e.target.value })} /></label><label>Student ID<input value={newStudent.studentId} onChange={(e) => setNewStudent({ ...newStudent, studentId: e.target.value })} placeholder="RSK-0001" /></label><label>Private lookup code<input value={newStudent.lookupCode} onChange={(e) => setNewStudent({ ...newStudent, lookupCode: e.target.value })} minLength={8} /></label><label>Current belt<select value={newStudent.currentBelt} onChange={(e) => setNewStudent({ ...newStudent, currentBelt: e.target.value })}>{belts.map((belt) => <option key={belt}>{belt}</option>)}</select></label><label>Belt colour<select value={newStudent.beltColor} onChange={(e) => setNewStudent({ ...newStudent, beltColor: e.target.value })}>{colors.map((color) => <option key={color}>{color}</option>)}</select></label><label className="check-line"><input type="checkbox" checked={newStudent.guardianConsent} onChange={(e) => setNewStudent({ ...newStudent, guardianConsent: e.target.checked })} /> Guardian consent recorded</label><button className="btn-primary"><UserPlus size={17} /> Add student</button></form></details>
        {detail ? <>
          <section className="student-editor"><header><div><p className="folio-mark">{detail.student.public_student_id}</p><h2>{detail.student.display_name}</h2></div><span>{detail.student.total_hours || students.find((item) => item.id === detail.student.id)?.total_hours || 0} verified hours</span></header><div className="admin-form-grid"><label>Display name<input value={detail.student.display_name} onChange={(e) => updateStudent({ display_name: e.target.value })} /></label><label>Current belt<select value={detail.student.current_belt} onChange={(e) => updateStudent({ current_belt: e.target.value })}>{belts.map((belt) => <option key={belt}>{belt}</option>)}</select></label><label>Belt colour<select value={detail.student.belt_color} onChange={(e) => updateStudent({ belt_color: e.target.value })}>{colors.map((color) => <option key={color}>{color}</option>)}</select></label><label className="upload-line"><Upload size={17} /> Replace profile photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => uploadProfile(e.target.files?.[0])} /></label><label className="check-line"><input type="checkbox" checked={Boolean(detail.student.profile_image_consent)} onChange={(e) => updateStudent({ profile_image_consent: Number(e.target.checked) })} /> Photo may be shown (consent recorded)</label><label className="check-line"><input type="checkbox" checked={Boolean(detail.student.guardian_consent)} onChange={(e) => updateStudent({ guardian_consent: Number(e.target.checked) })} /> Guardian consent recorded</label><label className="check-line"><input type="checkbox" checked={Boolean(detail.student.public_visible)} onChange={(e) => updateStudent({ public_visible: Number(e.target.checked) })} /> Record lookup enabled</label><label className="check-line"><input type="checkbox" checked={Boolean(detail.student.active)} onChange={(e) => updateStudent({ active: Number(e.target.checked) })} /> Student active</label></div><button className="btn-primary" onClick={saveStudent}>Save student record</button></section>
          <div className="admin-workflow-pair"><details className="admin-workflow"><summary><GraduationCap size={20} /> Record belt examination</summary><form onSubmit={addExam} className="admin-form-grid"><label>Date<input type="date" value={exam.date} onChange={(e) => setExam({ ...exam, date: e.target.value })} /></label><label>Belt or rank<select value={exam.belt} onChange={(e) => setExam({ ...exam, belt: e.target.value })}><option value="">Choose…</option>{belts.map((belt) => <option key={belt}>{belt}</option>)}</select></label><label>Belt colour<select value={exam.beltColor} onChange={(e) => setExam({ ...exam, beltColor: e.target.value })}>{colors.map((color) => <option key={color}>{color}</option>)}</select></label><label>Examiner<input value={exam.examiner} onChange={(e) => setExam({ ...exam, examiner: e.target.value })} /></label><label className="admin-span-2">Public note<textarea value={exam.publicNotes} onChange={(e) => setExam({ ...exam, publicNotes: e.target.value })} /></label><label className="admin-span-2">Internal note (never public)<textarea value={exam.internalNotes} onChange={(e) => setExam({ ...exam, internalNotes: e.target.value })} /></label><label className="check-line"><input type="checkbox" checked={exam.updateCurrentBelt} onChange={(e) => setExam({ ...exam, updateCurrentBelt: e.target.checked })} /> Update current belt</label><button className="btn-primary"><BadgePlus size={17} /> Save examination</button></form></details><details className="admin-workflow"><summary><Clock3 size={20} /> Add training hours</summary><form onSubmit={addHours} className="admin-form-grid"><label>Date or period start<input type="date" value={hours.date} onChange={(e) => setHours({ ...hours, date: e.target.value })} /></label><label>Period end (optional)<input type="date" value={hours.periodEnd} onChange={(e) => setHours({ ...hours, periodEnd: e.target.value })} /></label><label>Verified hours<input type="number" min="0.25" max="1000" step="0.25" value={hours.hours} onChange={(e) => setHours({ ...hours, hours: e.target.value })} /></label><label>Source or reason<input value={hours.source} onChange={(e) => setHours({ ...hours, source: e.target.value })} /></label><label className="admin-span-2">Internal explanation<textarea value={hours.internalNote} onChange={(e) => setHours({ ...hours, internalNote: e.target.value })} /></label><button className="btn-primary"><Clock3 size={17} /> Add hours</button></form></details></div>
          <section className="share-manager"><header><QrCode size={24} /><div><h3>Public QR sharing</h3><p>Generate a random, revocable link. The QR never contains a name, lookup code or database ID.</p></div></header><div className="editorial-actions"><button className="btn-primary" onClick={generateShare}>{detail.student.sharing_active ? "Regenerate share link" : "Generate share link"}</button>{detail.student.sharing_active ? <button className="btn-secondary" onClick={revokeShare}>Revoke sharing</button> : null}</div>{shareUrl ? <div className="share-manager__result">{qr ? <img src={qr} alt="Student share QR code" /> : null}<div><label>Share URL<input readOnly value={shareUrl} onFocus={(e) => e.currentTarget.select()} /></label><button className="text-link" onClick={() => window.print()}><Printer size={16} /> Print QR</button><a className="text-link" href={shareUrl} target="_blank" rel="noopener noreferrer">Preview public record</a></div></div> : null}</section>
        </> : <div className="student-empty"><span>生</span><h2>Select a student</h2><p>Choose a record from the list, or add a new student above.</p></div>}
      </main>
    </div>
  </section>;
}
