// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export const imageMetadata = {
  "/backgrounds/manuscript-desktop": [
    1536,
    1024,
    [
      640,
      1280,
      1536
    ]
  ],
  "/backgrounds/manuscript-mobile": [
    853,
    1844,
    [
      640,
      853
    ]
  ],
  "/cmu/aikido-cmu-club": [
    483,
    654,
    [
      483
    ]
  ],
  "/cmu/aikido-cmu-history": [
    732,
    498,
    [
      640,
      732
    ]
  ],
  "/cmu/aikido-cmu-practice-1": [
    323,
    448,
    [
      323
    ]
  ],
  "/cmu/aikido-cmu-practice-2": [
    282,
    399,
    [
      282
    ]
  ],
  "/cmu/aikido-cmu-practice-wide": [
    609,
    256,
    [
      609
    ]
  ],
  "/cmu/cmu-sub-logo": [
    151,
    214,
    [
      151
    ]
  ],
  "/community/community-reading": [
    820,
    342,
    [
      640,
      820
    ]
  ],
  "/community/library-books": [
    1600,
    1066,
    [
      640,
      1280,
      1600
    ]
  ],
  "/community/open-book": [
    1024,
    512,
    [
      640,
      1024
    ]
  ],
  "/community/reading-group": [
    1567,
    1045,
    [
      640,
      1280,
      1567
    ]
  ],
  "/dojo-photos/aikido-breakfall": [
    1600,
    1067,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/aikido-hero-new": [
    1881,
    836,
    [
      640,
      1280,
      1881
    ]
  ],
  "/dojo-photos/aikido-jo-training": [
    1600,
    1067,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/aikido-pin": [
    1600,
    2133,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/aikido-seminar-demo": [
    1600,
    1600,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/aikido-seminar-sumi-v2": [
    1254,
    1254,
    [
      640,
      1254
    ]
  ],
  "/dojo-photos/aikido-tanto-technique": [
    1600,
    1067,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/aikido-training-pin-2x": [
    1600,
    2133,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/aikido-wristlock": [
    1600,
    1927,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/belt-promotion-test": [
    949,
    1658,
    [
      640,
      949
    ]
  ],
  "/dojo-photos/image-community": [
    1448,
    1086,
    [
      640,
      1280,
      1448
    ]
  ],
  "/dojo-photos/kids-around-green-belt": [
    1448,
    1086,
    [
      640,
      1280,
      1448
    ]
  ],
  "/dojo-photos/new-hero-poster": [
    1672,
    941,
    [
      640,
      1280,
      1672
    ]
  ],
  "/dojo-photos/pcf": [
    1459,
    1078,
    [
      640,
      1280,
      1459
    ]
  ],
  "/dojo-photos/renshinkan-koi-pond-upscaled": [
    1600,
    2133,
    [
      640,
      1280,
      1600
    ]
  ],
  "/dojo-photos/schedule": [
    1476,
    1066,
    [
      640,
      1280,
      1476
    ]
  ],
  "/dojo-photos/support": [
    1402,
    1122,
    [
      640,
      1280,
      1402
    ]
  ],
  "/dojo-photos/workshop-location-courtyard": [
    1086,
    1448,
    [
      640,
      1086
    ]
  ],
  "/dojo-photos/workshop-location-dojo": [
    1448,
    1086,
    [
      640,
      1280,
      1448
    ]
  ],
  "/dojo-photos/workshop-location-garden": [
    1448,
    1086,
    [
      640,
      1280,
      1448
    ]
  ],
  "/history/morihei-ueshiba-1918": [
    700,
    707,
    [
      640,
      700
    ]
  ],
  "/history/morihei-ueshiba-1939": [
    600,
    865,
    [
      600
    ]
  ],
  "/history/o-sensei-aiki-shrine": [
    172,
    271,
    [
      172
    ]
  ],
  "/history/o-sensei-calligraphy": [
    294,
    231,
    [
      294
    ]
  ],
  "/history/o-sensei-hombu-prayer": [
    190,
    242,
    [
      190
    ]
  ],
  "/history/o-sensei-train": [
    272,
    180,
    [
      272
    ]
  ],
  "/history/o-sensei-walking": [
    174,
    271,
    [
      174
    ]
  ],
  "/history/sokaku-takeda-1888": [
    751,
    1099,
    [
      640,
      751
    ]
  ],
  "/instructors/kop-narumol": [
    1600,
    2133,
    [
      640,
      1280,
      1600
    ]
  ],
  "/instructors/major-kittisak-siriparp": [
    1086,
    1448,
    [
      640,
      1086
    ]
  ],
  "/instructors/major-kittisak-siriparp-current": [
    1086,
    1448,
    [
      640,
      1086
    ]
  ],
  "/instructors/siriphorn-manokeaw-current": [
    1086,
    1448,
    [
      640,
      1086
    ]
  ],
  "/instructors/sombat-tapanya": [
    1600,
    2133,
    [
      640,
      1280,
      1600
    ]
  ],
  "/instructors/teerarat-boripantakul": [
    1600,
    2133,
    [
      640,
      1280,
      1600
    ]
  ],
  "/past-events/463872355_27264339496544926_6495392107844493594_n": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/aikido_demonstration_stage_action_01": [
    960,
    542,
    [
      640,
      960
    ]
  ],
  "/past-events/aikido_event_large_group_stage_01": [
    960,
    584,
    [
      640,
      960
    ]
  ],
  "/past-events/cleanupday": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-001": [
    206,
    206,
    [
      206
    ]
  ],
  "/past-events/misc-gallery/history-photo-002": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-003": [
    960,
    542,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-004": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-005": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-006": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-007": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-008": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-009": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-010": [
    960,
    640,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-011": [
    960,
    640,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-012": [
    960,
    576,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-013": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-014": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-015": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-016": [
    720,
    960,
    [
      640,
      720
    ]
  ],
  "/past-events/misc-gallery/history-photo-017": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-018": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-019": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-020": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-021": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-022": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-023": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-024": [
    720,
    960,
    [
      640,
      720
    ]
  ],
  "/past-events/misc-gallery/history-photo-025": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-026": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-027": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-028": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-029": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-030": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-031": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-032": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-033": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-034": [
    636,
    636,
    [
      636
    ]
  ],
  "/past-events/misc-gallery/history-photo-035": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-036": [
    720,
    477,
    [
      640,
      720
    ]
  ],
  "/past-events/misc-gallery/history-photo-037": [
    960,
    640,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-038": [
    960,
    643,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-039": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/misc-gallery/history-photo-040": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/past-events/training at old cmu center": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/pcf-aikido/aikido-class": [
    1600,
    1067,
    [
      640,
      1280,
      1600
    ]
  ],
  "/pcf-aikido/bokken-rack": [
    1600,
    1066,
    [
      640,
      1280,
      1600
    ]
  ],
  "/pcf-aikido/class-schedule": [
    1600,
    1600,
    [
      640,
      1280,
      1600
    ]
  ],
  "/pcf-aikido/dojo-exterior": [
    1600,
    1066,
    [
      640,
      1280,
      1600
    ]
  ],
  "/pcf-aikido/dojo-sign": [
    1600,
    1066,
    [
      640,
      1280,
      1600
    ]
  ],
  "/pcf-aikido/jo-bokken": [
    1600,
    1066,
    [
      640,
      1280,
      1600
    ]
  ],
  "/pcf-aikido/kamiza": [
    1600,
    1066,
    [
      640,
      1280,
      1600
    ]
  ],
  "/peace-culture/peace-culture-foundation-logo": [
    150,
    150,
    [
      150
    ]
  ],
  "/renshinkan-build/crops/early-columns-february-2012": [
    976,
    509,
    [
      640,
      976
    ]
  ],
  "/renshinkan-build/crops/finished-wood-floor-november-2012": [
    978,
    700,
    [
      640,
      978
    ]
  ],
  "/renshinkan-build/crops/first-ukemi-april-2013": [
    972,
    867,
    [
      640,
      972
    ]
  ],
  "/renshinkan-build/crops/foundation-formwork-january-2012": [
    976,
    577,
    [
      640,
      976
    ]
  ],
  "/renshinkan-build/crops/garden-view-may-2012": [
    818,
    1175,
    [
      640,
      818
    ]
  ],
  "/renshinkan-build/crops/interclub-community-august-2013": [
    478,
    592,
    [
      478
    ]
  ],
  "/renshinkan-build/crops/kamiza-visit-january-2013": [
    973,
    700,
    [
      640,
      973
    ]
  ],
  "/renshinkan-build/crops/night-exterior-november-2012": [
    978,
    710,
    [
      640,
      978
    ]
  ],
  "/renshinkan-build/crops/opening-practice-april-2013": [
    974,
    712,
    [
      640,
      974
    ]
  ],
  "/renshinkan-build/crops/roof-frame-may-2012": [
    978,
    710,
    [
      640,
      978
    ]
  ],
  "/renshinkan-build/crops/site-layout-december-2011": [
    976,
    500,
    [
      640,
      976
    ]
  ],
  "/renshinkan-build/crops/sunlit-empty-dojo-january-2013": [
    978,
    702,
    [
      640,
      978
    ]
  ],
  "/renshinkan-build/crops/tatami-installation-april-2013": [
    976,
    746,
    [
      640,
      976
    ]
  ],
  "/renshinkan-build/crops/tatami-stacked-april-2013": [
    976,
    697,
    [
      640,
      976
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-001": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-002": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-003": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-004": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-005": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-006": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-007": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-008": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-009": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-010": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-011": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-012": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-013": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-014": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-015": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-016": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-017": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-018": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-019": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-020": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-021": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-022": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-023": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-024": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-025": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-026": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-027": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-028": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-029": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-030": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-031": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-032": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-033": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-034": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-035": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-036": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-037": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-038": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-039": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-040": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-041": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-042": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-043": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-044": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-045": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-046": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-047": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-048": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-049": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-050": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-051": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-052": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-053": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-054": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-055": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-056": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-057": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-058": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-059": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-060": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-061": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-062": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-063": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-064": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-065": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-066": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-067": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-068": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-069": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-070": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-071": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-072": [
    960,
    540,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-073": [
    960,
    540,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-074": [
    960,
    540,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-075": [
    960,
    540,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-076": [
    960,
    540,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-077": [
    960,
    540,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-078": [
    960,
    540,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-079": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-080": [
    908,
    960,
    [
      640,
      908
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-081": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-082": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-083": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-084": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-085": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-086": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-087": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-088": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-089": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-090": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-091": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-092": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-093": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-094": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-095": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-096": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-097": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-098": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-099": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-100": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-101": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-102": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-103": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-104": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-105": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-106": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-107": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-108": [
    949,
    855,
    [
      640,
      949
    ]
  ],
  "/renshinkan-gallery/belt-ceremony/belt-ceremony-109": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_mixed_group_01": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_mixed_group_02": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_mixed_group_03": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_three_students_01": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_two_students_01": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_two_students_02": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_two_students_03": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_certificate_two_students_04": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/belt-graduation/belt_graduation_large_class_group_01": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/class-photos/class_group_dojo_closeup_01": [
    1842,
    1034,
    [
      640,
      1280,
      1842
    ]
  ],
  "/renshinkan-gallery/class-photos/class_group_dojo_front_wall_01": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/class-photos/class_group_dojo_wide_01": [
    1920,
    1440,
    [
      640,
      1280,
      1920
    ]
  ],
  "/renshinkan-gallery/class-photos/class_group_dojo_wide_02": [
    1920,
    1440,
    [
      640,
      1280,
      1920
    ]
  ],
  "/renshinkan-gallery/class-photos/class_group_dojo_yellow_mat_01": [
    1476,
    1109,
    [
      640,
      1280,
      1476
    ]
  ],
  "/renshinkan-gallery/class-photos/on_the_mat_01": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/class-photos/on_the_mat_02": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-001": [
    1280,
    960,
    [
      640,
      1280
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-002": [
    1280,
    719,
    [
      640,
      1280
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-003": [
    1280,
    962,
    [
      640,
      1280
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-004": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-005": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-006": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-007": [
    960,
    584,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-008": [
    960,
    718,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-009": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-010": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-011": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-012": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-013": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-gallery/group-photos/group-photo-014": [
    960,
    720,
    [
      640,
      960
    ]
  ],
  "/renshinkan-logo": [
    384,
    384,
    [
      384
    ]
  ]
} as const;

export type ImageMetadataKey = keyof typeof imageMetadata;
